{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_SUPPLIER',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_SF1_SF1SUPPLIER_INIT', 'STG_SF1_SF1SUPPLIER_PREP_DELETE']
	)
}}
select * from (
	SELECT 
		  "STG_CURR_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "STG_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_SRC"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_SRC"."S_SUPPKEY" AS "S_SUPPKEY"
		, "STG_CURR_SRC"."SUPPLIER_BK" AS "SUPPLIER_BK"
		, "STG_CURR_SRC"."S_NAME" AS "S_NAME"
		, "STG_CURR_SRC"."S_ADDRESS" AS "S_ADDRESS"
		, "STG_CURR_SRC"."S_NATIONKEY" AS "S_NATIONKEY"
		, "STG_CURR_SRC"."S_PHONE" AS "S_PHONE"
		, "STG_CURR_SRC"."S_ACCTBAL" AS "S_ACCTBAL"
		, "STG_CURR_SRC"."S_COMMENT" AS "S_COMMENT"
		, "STG_CURR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER_CURR') }} "STG_CURR_SRC"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_CURR_PREV" AS 
	( 
		SELECT 
			  "STG_CURR_INS"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_CURR_INS"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_INS"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_INS"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_INS"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('I' ) AS "JRN_FLAG"
			, "STG_CURR_INS"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_INS"."S_SUPPKEY" AS "S_SUPPKEY"
			, "STG_CURR_INS"."SUPPLIER_BK" AS "SUPPLIER_BK"
			, "STG_CURR_INS"."S_NAME" AS "S_NAME"
			, "STG_CURR_INS"."S_ADDRESS" AS "S_ADDRESS"
			, "STG_CURR_INS"."S_NATIONKEY" AS "S_NATIONKEY"
			, "STG_CURR_INS"."S_PHONE" AS "S_PHONE"
			, "STG_CURR_INS"."S_ACCTBAL" AS "S_ACCTBAL"
			, "STG_CURR_INS"."S_COMMENT" AS "S_COMMENT"
			, "STG_CURR_INS"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER_CURR') }} "STG_CURR_INS"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER_PREV') }} "STG_PREV_INS" ON  "STG_PREV_INS"."SUPPLIER_HKEY" = "STG_CURR_INS"."SUPPLIER_HKEY"
		WHERE  "STG_PREV_INS"."SUPPLIER_HKEY" IS NULL
		UNION ALL 
		SELECT 
			  "STG_CURR_UPD"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_CURR_UPD"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_UPD"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_UPD"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_UPD"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('U' ) AS "JRN_FLAG"
			, "STG_CURR_UPD"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_UPD"."S_SUPPKEY" AS "S_SUPPKEY"
			, "STG_CURR_UPD"."SUPPLIER_BK" AS "SUPPLIER_BK"
			, "STG_CURR_UPD"."S_NAME" AS "S_NAME"
			, "STG_CURR_UPD"."S_ADDRESS" AS "S_ADDRESS"
			, "STG_CURR_UPD"."S_NATIONKEY" AS "S_NATIONKEY"
			, "STG_CURR_UPD"."S_PHONE" AS "S_PHONE"
			, "STG_CURR_UPD"."S_ACCTBAL" AS "S_ACCTBAL"
			, "STG_CURR_UPD"."S_COMMENT" AS "S_COMMENT"
			, "STG_CURR_UPD"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER_CURR') }} "STG_CURR_UPD"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER_PREV') }} "STG_PREV_UPD" ON  "STG_PREV_UPD"."SUPPLIER_HKEY" = "STG_CURR_UPD"."SUPPLIER_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_NULL" ON  "MEX_NULL"."RECORD_TYPE" = 'N'
		WHERE  COALESCE("STG_PREV_UPD"."S_SUPPKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."S_SUPPKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."S_ADDRESS", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."S_ADDRESS", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."S_NATIONKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."S_NATIONKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."S_PHONE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."S_PHONE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."S_ACCTBAL", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."S_ACCTBAL", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."S_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."S_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))
		UNION ALL 
		SELECT 
			  "STG_PREV_DEL"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_PREV_DEL"."SRC_BK" AS "SRC_BK"
			, "STG_PREV_DEL"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('D' ) AS "JRN_FLAG"
			, "STG_PREV_DEL"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_PREV_DEL"."S_SUPPKEY" AS "S_SUPPKEY"
			, "STG_PREV_DEL"."SUPPLIER_BK" AS "SUPPLIER_BK"
			, "STG_PREV_DEL"."S_NAME" AS "S_NAME"
			, "STG_PREV_DEL"."S_ADDRESS" AS "S_ADDRESS"
			, "STG_PREV_DEL"."S_NATIONKEY" AS "S_NATIONKEY"
			, "STG_PREV_DEL"."S_PHONE" AS "S_PHONE"
			, "STG_PREV_DEL"."S_ACCTBAL" AS "S_ACCTBAL"
			, "STG_PREV_DEL"."S_COMMENT" AS "S_COMMENT"
			, "STG_PREV_DEL"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER_PREV') }} "STG_PREV_DEL"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER_CURR') }} "STG_CURR_DEL" ON  "STG_PREV_DEL"."SUPPLIER_HKEY" = "STG_CURR_DEL"."SUPPLIER_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		WHERE  "STG_CURR_DEL"."SUPPLIER_HKEY" IS NULL
	)
	SELECT 
		  "STG_CURR_PREV"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "STG_CURR_PREV"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_PREV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_PREV"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_PREV"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_PREV"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_PREV"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_PREV"."S_SUPPKEY" AS "S_SUPPKEY"
		, "STG_CURR_PREV"."SUPPLIER_BK" AS "SUPPLIER_BK"
		, "STG_CURR_PREV"."S_NAME" AS "S_NAME"
		, "STG_CURR_PREV"."S_ADDRESS" AS "S_ADDRESS"
		, "STG_CURR_PREV"."S_NATIONKEY" AS "S_NATIONKEY"
		, "STG_CURR_PREV"."S_PHONE" AS "S_PHONE"
		, "STG_CURR_PREV"."S_ACCTBAL" AS "S_ACCTBAL"
		, "STG_CURR_PREV"."S_COMMENT" AS "S_COMMENT"
		, "STG_CURR_PREV"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "STG_CURR_PREV" "STG_CURR_PREV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'