{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} DELETE  FROM {{ this }} "STG_DL_DEL_TGT"	WHERE  NOT EXISTS	(		SELECT 			  1 AS "DUMMY"		FROM {{ source(\'VS_DEMO_TC_MTD\', \'LOAD_CYCLE_INFO\') }} "LCI_DEL_SRC"		INNER JOIN {{ source(\'VS_DEMO_TC_STG\', \'ORDER_CUST_CURR\') }} "STG_DL_DEL_CURR_SRC" ON  "LCI_DEL_SRC"."LOAD_CYCLE_ID" = "STG_DL_DEL_CURR_SRC"."LOAD_CYCLE_ID"	) {% endif %}'
		],
		alias='ORDER_CUST_PREV',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_DL_SF1_ORDER_CUST_INCR']
	)
}}
select * from (
	SELECT 
		  "STG_DL_CURR_SRC"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
		, "STG_DL_CURR_SRC"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
		, "STG_DL_CURR_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
		, "STG_DL_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_DL_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_DL_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_DL_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_DL_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_DL_CURR_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
		, "STG_DL_CURR_SRC"."O_CUSTKEY" AS "O_CUSTKEY"
		, "STG_DL_CURR_SRC"."C_NAME_FK_OCUSTKEY_BK" AS "C_NAME_FK_OCUSTKEY_BK"
		, "STG_DL_CURR_SRC"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
		, "STG_DL_CURR_SRC"."C_NAME" AS "C_NAME"
	FROM {{ source('VS_DEMO_TC_STG', 'ORDER_CUST_CURR') }} "STG_DL_CURR_SRC"
	LEFT OUTER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  "STG_DL_CURR_SRC"."LOAD_CYCLE_ID" = "LCI_SRC"."LOAD_CYCLE_ID"
	LEFT OUTER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC_CURR_TO_PREV" ON  "MEX_SRC_CURR_TO_PREV"."LOAD_CYCLE_ID" = TO_CHAR("STG_DL_CURR_SRC"."LOAD_CYCLE_ID" )
	WHERE  "LCI_SRC"."LOAD_CYCLE_ID" IS NULL AND "MEX_SRC_CURR_TO_PREV"."LOAD_CYCLE_ID" IS NULL

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'