{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='ORDER_CUST',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_DL_SF1_ORDER_CUST_INIT', 'STG_DL_SF1_ORDER_CUST_PREP_DELETE']
	)
}}
select * from (
	SELECT 
		  "STG_DL_CURR_SRC"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
		, "STG_DL_CURR_SRC"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
		, "STG_DL_CURR_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
		, "STG_DL_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_DL_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_DL_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_DL_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_DL_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_DL_CURR_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
		, "STG_DL_CURR_SRC"."O_CUSTKEY" AS "O_CUSTKEY"
		, "STG_DL_CURR_SRC"."C_NAME_FK_OCUSTKEY_BK" AS "C_NAME_FK_OCUSTKEY_BK"
		, "STG_DL_CURR_SRC"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
		, "STG_DL_CURR_SRC"."C_NAME" AS "C_NAME"
	FROM {{ ref('VS_DEMO_TC_STG_ORDER_CUST_CURR') }} "STG_DL_CURR_SRC"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_DL_CURR_PREV" AS 
	( 
		SELECT 
			  "STG_DL_CURR_INS"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "STG_DL_CURR_INS"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "STG_DL_CURR_INS"."ORDER_HKEY" AS "ORDER_HKEY"
			, "STG_DL_CURR_INS"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_DL_CURR_INS"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_DL_CURR_INS"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('I' ) AS "JRN_FLAG"
			, "STG_DL_CURR_INS"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_DL_CURR_INS"."O_ORDERKEY" AS "O_ORDERKEY"
			, "STG_DL_CURR_INS"."O_CUSTKEY" AS "O_CUSTKEY"
			, "STG_DL_CURR_INS"."C_NAME_FK_OCUSTKEY_BK" AS "C_NAME_FK_OCUSTKEY_BK"
			, "STG_DL_CURR_INS"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
			, "STG_DL_CURR_INS"."C_NAME" AS "C_NAME"
		FROM {{ ref('VS_DEMO_TC_STG_ORDER_CUST_CURR') }} "STG_DL_CURR_INS"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_ORDER_CUST_PREV') }} "STG_DL_PREV_INS" ON  "STG_DL_PREV_INS"."LND_ORDERCUST_HKEY" = "STG_DL_CURR_INS"."LND_ORDERCUST_HKEY"
		WHERE  "STG_DL_PREV_INS"."LND_ORDERCUST_HKEY" IS NULL
		UNION ALL 
		SELECT 
			  "STG_DL_CURR_UPD"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "STG_DL_CURR_UPD"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "STG_DL_CURR_UPD"."ORDER_HKEY" AS "ORDER_HKEY"
			, "STG_DL_CURR_UPD"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_DL_CURR_UPD"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_DL_CURR_UPD"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('U' ) AS "JRN_FLAG"
			, "STG_DL_CURR_UPD"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_DL_CURR_UPD"."O_ORDERKEY" AS "O_ORDERKEY"
			, "STG_DL_CURR_UPD"."O_CUSTKEY" AS "O_CUSTKEY"
			, "STG_DL_CURR_UPD"."C_NAME_FK_OCUSTKEY_BK" AS "C_NAME_FK_OCUSTKEY_BK"
			, "STG_DL_CURR_UPD"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
			, "STG_DL_CURR_UPD"."C_NAME" AS "C_NAME"
		FROM {{ ref('VS_DEMO_TC_STG_ORDER_CUST_CURR') }} "STG_DL_CURR_UPD"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_ORDER_CUST_PREV') }} "STG_DL_PREV_UPD" ON  "STG_DL_PREV_UPD"."LND_ORDERCUST_HKEY" = "STG_DL_CURR_UPD"."LND_ORDERCUST_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_NULL" ON  "MEX_NULL"."RECORD_TYPE" = 'N'
		WHERE  COALESCE("STG_DL_PREV_UPD"."O_ORDERKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_DL_CURR_UPD"."O_ORDERKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_DL_PREV_UPD"."O_CUSTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_DL_CURR_UPD"."O_CUSTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_DL_PREV_UPD"."C_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."C_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_DL_PREV_UPD"."CUSTOMER_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."CUSTOMER_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_DL_PREV_UPD"."ORDER_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."ORDER_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))
		UNION ALL 
		SELECT 
			  "STG_DL_PREV_DEL"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "STG_DL_PREV_DEL"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "STG_DL_PREV_DEL"."ORDER_HKEY" AS "ORDER_HKEY"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_DL_PREV_DEL"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('D' ) AS "JRN_FLAG"
			, "STG_DL_PREV_DEL"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_DL_PREV_DEL"."O_ORDERKEY" AS "O_ORDERKEY"
			, "STG_DL_PREV_DEL"."O_CUSTKEY" AS "O_CUSTKEY"
			, "STG_DL_PREV_DEL"."C_NAME_FK_OCUSTKEY_BK" AS "C_NAME_FK_OCUSTKEY_BK"
			, "STG_DL_PREV_DEL"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
			, "STG_DL_PREV_DEL"."C_NAME" AS "C_NAME"
		FROM {{ ref('VS_DEMO_TC_STG_ORDER_CUST_PREV') }} "STG_DL_PREV_DEL"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_ORDER_CUST_CURR') }} "STG_DL_CURR_DEL" ON  "STG_DL_PREV_DEL"."LND_ORDERCUST_HKEY" = "STG_DL_CURR_DEL"."LND_ORDERCUST_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		WHERE  "STG_DL_CURR_DEL"."LND_ORDERCUST_HKEY" IS NULL
	)
	SELECT 
		  "STG_DL_CURR_PREV"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
		, "STG_DL_CURR_PREV"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
		, "STG_DL_CURR_PREV"."ORDER_HKEY" AS "ORDER_HKEY"
		, "STG_DL_CURR_PREV"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_DL_CURR_PREV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_DL_CURR_PREV"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_DL_CURR_PREV"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_DL_CURR_PREV"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_DL_CURR_PREV"."O_ORDERKEY" AS "O_ORDERKEY"
		, "STG_DL_CURR_PREV"."O_CUSTKEY" AS "O_CUSTKEY"
		, "STG_DL_CURR_PREV"."C_NAME_FK_OCUSTKEY_BK" AS "C_NAME_FK_OCUSTKEY_BK"
		, "STG_DL_CURR_PREV"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
		, "STG_DL_CURR_PREV"."C_NAME" AS "C_NAME"
	FROM "STG_DL_CURR_PREV" "STG_DL_CURR_PREV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'