{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='ORDER',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_SF1_ORDER_INIT', 'STG_SF1_ORDER_PREP_DELETE']
	)
}}
select * from (
	SELECT 
		  "STG_CURR_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
		, "STG_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_SRC"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
		, "STG_CURR_SRC"."ORDER_BK" AS "ORDER_BK"
		, "STG_CURR_SRC"."C_NAME" AS "C_NAME"
		, "STG_CURR_SRC"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
		, "STG_CURR_SRC"."O_TOTALPRICE" AS "O_TOTALPRICE"
		, "STG_CURR_SRC"."O_ORDERDATE" AS "O_ORDERDATE"
		, "STG_CURR_SRC"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
		, "STG_CURR_SRC"."O_CLERK" AS "O_CLERK"
		, "STG_CURR_SRC"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
		, "STG_CURR_SRC"."O_COMMENT" AS "O_COMMENT"
		, "STG_CURR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_STG_ORDER_CURR') }} "STG_CURR_SRC"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_CURR_PREV" AS 
	( 
		SELECT 
			  "STG_CURR_INS"."ORDER_HKEY" AS "ORDER_HKEY"
			, "STG_CURR_INS"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_INS"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_INS"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_INS"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('I' ) AS "JRN_FLAG"
			, "STG_CURR_INS"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_INS"."O_ORDERKEY" AS "O_ORDERKEY"
			, "STG_CURR_INS"."ORDER_BK" AS "ORDER_BK"
			, "STG_CURR_INS"."C_NAME" AS "C_NAME"
			, "STG_CURR_INS"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
			, "STG_CURR_INS"."O_TOTALPRICE" AS "O_TOTALPRICE"
			, "STG_CURR_INS"."O_ORDERDATE" AS "O_ORDERDATE"
			, "STG_CURR_INS"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
			, "STG_CURR_INS"."O_CLERK" AS "O_CLERK"
			, "STG_CURR_INS"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
			, "STG_CURR_INS"."O_COMMENT" AS "O_COMMENT"
			, "STG_CURR_INS"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_ORDER_CURR') }} "STG_CURR_INS"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_ORDER_PREV') }} "STG_PREV_INS" ON  "STG_PREV_INS"."ORDER_HKEY" = "STG_CURR_INS"."ORDER_HKEY"
		WHERE  "STG_PREV_INS"."ORDER_HKEY" IS NULL
		UNION ALL 
		SELECT 
			  "STG_CURR_UPD"."ORDER_HKEY" AS "ORDER_HKEY"
			, "STG_CURR_UPD"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_UPD"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_UPD"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_UPD"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('U' ) AS "JRN_FLAG"
			, "STG_CURR_UPD"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_UPD"."O_ORDERKEY" AS "O_ORDERKEY"
			, "STG_CURR_UPD"."ORDER_BK" AS "ORDER_BK"
			, "STG_CURR_UPD"."C_NAME" AS "C_NAME"
			, "STG_CURR_UPD"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
			, "STG_CURR_UPD"."O_TOTALPRICE" AS "O_TOTALPRICE"
			, "STG_CURR_UPD"."O_ORDERDATE" AS "O_ORDERDATE"
			, "STG_CURR_UPD"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
			, "STG_CURR_UPD"."O_CLERK" AS "O_CLERK"
			, "STG_CURR_UPD"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
			, "STG_CURR_UPD"."O_COMMENT" AS "O_COMMENT"
			, "STG_CURR_UPD"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_ORDER_CURR') }} "STG_CURR_UPD"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_ORDER_PREV') }} "STG_PREV_UPD" ON  "STG_PREV_UPD"."ORDER_HKEY" = "STG_CURR_UPD"."ORDER_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_NULL" ON  "MEX_NULL"."RECORD_TYPE" = 'N'
		WHERE  COALESCE("STG_PREV_UPD"."O_ORDERKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."O_ORDERKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."C_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."C_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."O_ORDERSTATUS", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."O_ORDERSTATUS", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."O_TOTALPRICE", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."O_TOTALPRICE", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."O_ORDERDATE", TO_DATE("MEX_NULL"."ATTRIBUTE_DATE", 'DD/MM/YYYY'))!= COALESCE("STG_CURR_UPD"."O_ORDERDATE", TO_DATE("MEX_NULL"."ATTRIBUTE_DATE", 'DD/MM/YYYY')) OR  COALESCE("STG_PREV_UPD"."O_ORDERPRIORITY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."O_ORDERPRIORITY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."O_CLERK", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."O_CLERK", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."O_SHIPPRIORITY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."O_SHIPPRIORITY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."O_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."O_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))
		UNION ALL 
		SELECT 
			  "STG_PREV_DEL"."ORDER_HKEY" AS "ORDER_HKEY"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_PREV_DEL"."SRC_BK" AS "SRC_BK"
			, "STG_PREV_DEL"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('D' ) AS "JRN_FLAG"
			, "STG_PREV_DEL"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_PREV_DEL"."O_ORDERKEY" AS "O_ORDERKEY"
			, "STG_PREV_DEL"."ORDER_BK" AS "ORDER_BK"
			, "STG_PREV_DEL"."C_NAME" AS "C_NAME"
			, "STG_PREV_DEL"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
			, "STG_PREV_DEL"."O_TOTALPRICE" AS "O_TOTALPRICE"
			, "STG_PREV_DEL"."O_ORDERDATE" AS "O_ORDERDATE"
			, "STG_PREV_DEL"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
			, "STG_PREV_DEL"."O_CLERK" AS "O_CLERK"
			, "STG_PREV_DEL"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
			, "STG_PREV_DEL"."O_COMMENT" AS "O_COMMENT"
			, "STG_PREV_DEL"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_ORDER_PREV') }} "STG_PREV_DEL"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_ORDER_CURR') }} "STG_CURR_DEL" ON  "STG_PREV_DEL"."ORDER_HKEY" = "STG_CURR_DEL"."ORDER_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		WHERE  "STG_CURR_DEL"."ORDER_HKEY" IS NULL
	)
	SELECT 
		  "STG_CURR_PREV"."ORDER_HKEY" AS "ORDER_HKEY"
		, "STG_CURR_PREV"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_PREV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_PREV"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_PREV"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_PREV"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_PREV"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_PREV"."O_ORDERKEY" AS "O_ORDERKEY"
		, "STG_CURR_PREV"."ORDER_BK" AS "ORDER_BK"
		, "STG_CURR_PREV"."C_NAME" AS "C_NAME"
		, "STG_CURR_PREV"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
		, "STG_CURR_PREV"."O_TOTALPRICE" AS "O_TOTALPRICE"
		, "STG_CURR_PREV"."O_ORDERDATE" AS "O_ORDERDATE"
		, "STG_CURR_PREV"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
		, "STG_CURR_PREV"."O_CLERK" AS "O_CLERK"
		, "STG_CURR_PREV"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
		, "STG_CURR_PREV"."O_COMMENT" AS "O_COMMENT"
		, "STG_CURR_PREV"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "STG_CURR_PREV" "STG_CURR_PREV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'