{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_PART',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_SF1_SF1PART_INIT', 'STG_SF1_SF1PART_PREP_DELETE']
	)
}}
select * from (
	SELECT 
		  "STG_CURR_SRC"."PART_HKEY" AS "PART_HKEY"
		, "STG_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_SRC"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_SRC"."P_PARTKEY" AS "P_PARTKEY"
		, "STG_CURR_SRC"."PART_BK" AS "PART_BK"
		, "STG_CURR_SRC"."P_NAME" AS "P_NAME"
		, "STG_CURR_SRC"."P_SIZE" AS "P_SIZE"
		, "STG_CURR_SRC"."P_MFGR" AS "P_MFGR"
		, "STG_CURR_SRC"."P_BRAND" AS "P_BRAND"
		, "STG_CURR_SRC"."P_TYPE" AS "P_TYPE"
		, "STG_CURR_SRC"."P_CONTAINER" AS "P_CONTAINER"
		, "STG_CURR_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "STG_CURR_SRC"."P_COMMENT" AS "P_COMMENT"
		, "STG_CURR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_STG_SF1_PART_CURR') }} "STG_CURR_SRC"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_CURR_PREV" AS 
	( 
		SELECT 
			  "STG_CURR_INS"."PART_HKEY" AS "PART_HKEY"
			, "STG_CURR_INS"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_INS"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_INS"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_INS"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('I' ) AS "JRN_FLAG"
			, "STG_CURR_INS"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_INS"."P_PARTKEY" AS "P_PARTKEY"
			, "STG_CURR_INS"."PART_BK" AS "PART_BK"
			, "STG_CURR_INS"."P_NAME" AS "P_NAME"
			, "STG_CURR_INS"."P_SIZE" AS "P_SIZE"
			, "STG_CURR_INS"."P_MFGR" AS "P_MFGR"
			, "STG_CURR_INS"."P_BRAND" AS "P_BRAND"
			, "STG_CURR_INS"."P_TYPE" AS "P_TYPE"
			, "STG_CURR_INS"."P_CONTAINER" AS "P_CONTAINER"
			, "STG_CURR_INS"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "STG_CURR_INS"."P_COMMENT" AS "P_COMMENT"
			, "STG_CURR_INS"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PART_CURR') }} "STG_CURR_INS"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_PART_PREV') }} "STG_PREV_INS" ON  "STG_PREV_INS"."PART_HKEY" = "STG_CURR_INS"."PART_HKEY"
		WHERE  "STG_PREV_INS"."PART_HKEY" IS NULL
		UNION ALL 
		SELECT 
			  "STG_CURR_UPD"."PART_HKEY" AS "PART_HKEY"
			, "STG_CURR_UPD"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_UPD"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_UPD"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_UPD"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('U' ) AS "JRN_FLAG"
			, "STG_CURR_UPD"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_UPD"."P_PARTKEY" AS "P_PARTKEY"
			, "STG_CURR_UPD"."PART_BK" AS "PART_BK"
			, "STG_CURR_UPD"."P_NAME" AS "P_NAME"
			, "STG_CURR_UPD"."P_SIZE" AS "P_SIZE"
			, "STG_CURR_UPD"."P_MFGR" AS "P_MFGR"
			, "STG_CURR_UPD"."P_BRAND" AS "P_BRAND"
			, "STG_CURR_UPD"."P_TYPE" AS "P_TYPE"
			, "STG_CURR_UPD"."P_CONTAINER" AS "P_CONTAINER"
			, "STG_CURR_UPD"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "STG_CURR_UPD"."P_COMMENT" AS "P_COMMENT"
			, "STG_CURR_UPD"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PART_CURR') }} "STG_CURR_UPD"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_SF1_PART_PREV') }} "STG_PREV_UPD" ON  "STG_PREV_UPD"."PART_HKEY" = "STG_CURR_UPD"."PART_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_NULL" ON  "MEX_NULL"."RECORD_TYPE" = 'N'
		WHERE  COALESCE("STG_PREV_UPD"."P_PARTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."P_PARTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."P_MFGR", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."P_MFGR", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."P_BRAND", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."P_BRAND", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."P_TYPE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."P_TYPE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."P_CONTAINER", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."P_CONTAINER", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."P_RETAILPRICE", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."P_RETAILPRICE", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."P_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."P_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))
		UNION ALL 
		SELECT 
			  "STG_PREV_DEL"."PART_HKEY" AS "PART_HKEY"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_PREV_DEL"."SRC_BK" AS "SRC_BK"
			, "STG_PREV_DEL"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('D' ) AS "JRN_FLAG"
			, "STG_PREV_DEL"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_PREV_DEL"."P_PARTKEY" AS "P_PARTKEY"
			, "STG_PREV_DEL"."PART_BK" AS "PART_BK"
			, "STG_PREV_DEL"."P_NAME" AS "P_NAME"
			, "STG_PREV_DEL"."P_SIZE" AS "P_SIZE"
			, "STG_PREV_DEL"."P_MFGR" AS "P_MFGR"
			, "STG_PREV_DEL"."P_BRAND" AS "P_BRAND"
			, "STG_PREV_DEL"."P_TYPE" AS "P_TYPE"
			, "STG_PREV_DEL"."P_CONTAINER" AS "P_CONTAINER"
			, "STG_PREV_DEL"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "STG_PREV_DEL"."P_COMMENT" AS "P_COMMENT"
			, "STG_PREV_DEL"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PART_PREV') }} "STG_PREV_DEL"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_PART_CURR') }} "STG_CURR_DEL" ON  "STG_PREV_DEL"."PART_HKEY" = "STG_CURR_DEL"."PART_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		WHERE  "STG_CURR_DEL"."PART_HKEY" IS NULL
	)
	SELECT 
		  "STG_CURR_PREV"."PART_HKEY" AS "PART_HKEY"
		, "STG_CURR_PREV"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_PREV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_PREV"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_PREV"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_PREV"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_PREV"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_PREV"."P_PARTKEY" AS "P_PARTKEY"
		, "STG_CURR_PREV"."PART_BK" AS "PART_BK"
		, "STG_CURR_PREV"."P_NAME" AS "P_NAME"
		, "STG_CURR_PREV"."P_SIZE" AS "P_SIZE"
		, "STG_CURR_PREV"."P_MFGR" AS "P_MFGR"
		, "STG_CURR_PREV"."P_BRAND" AS "P_BRAND"
		, "STG_CURR_PREV"."P_TYPE" AS "P_TYPE"
		, "STG_CURR_PREV"."P_CONTAINER" AS "P_CONTAINER"
		, "STG_CURR_PREV"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "STG_CURR_PREV"."P_COMMENT" AS "P_COMMENT"
		, "STG_CURR_PREV"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "STG_CURR_PREV" "STG_CURR_PREV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'