{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_PARTSUPP_CURR',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_DL_SF1_SF1PARTSUPP_INCR', 'STG_DL_SF1_SF1PARTSUPP_INIT']
	)
}}
select * from (
	WITH "DIST_IO_FK1" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_IO_SRC1"."PS_SUPPKEY" AS "PS_SUPPKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_IO_SRC1"
	)
	, "DIST_IO_FK2" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_IO_SRC2"."PS_PARTKEY" AS "PS_PARTKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_IO_SRC2"
	)
	, "SAT_SRC1" AS 
	( 
		SELECT 
			  "SAT_IO_SRC1"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "SAT_IO_SRC1"."S_SUPPKEY" AS "S_SUPPKEY"
			, MAX("SAT_IO_SRC1"."LOAD_DATE") AS "LOAD_DATE"
			, "SAT_IO_SRC1"."S_NAME" AS "S_NAME"
		FROM {{ source('RDV', 'S_SF1_SUPPLIER') }} "SAT_IO_SRC1"
		INNER JOIN "DIST_IO_FK1" "DIST_IO_FK1" ON  "DIST_IO_FK1"."PS_SUPPKEY" = "SAT_IO_SRC1"."S_SUPPKEY"
		GROUP BY  "SAT_IO_SRC1"."SUPPLIER_HKEY",  "SAT_IO_SRC1"."S_SUPPKEY",  "SAT_IO_SRC1"."S_NAME"
	)
	, "SAT_SRC2" AS 
	( 
		SELECT 
			  "SAT_IO_SRC2"."PART_HKEY" AS "PART_HKEY"
			, "SAT_IO_SRC2"."P_PARTKEY" AS "P_PARTKEY"
			, MAX("SAT_IO_SRC2"."LOAD_DATE") AS "LOAD_DATE"
			, "SAT_IO_SRC2"."P_NAME" AS "P_NAME"
			, "SAT_IO_SRC2"."P_SIZE" AS "P_SIZE"
		FROM {{ source('RDV', 'S_SF1_PART') }} "SAT_IO_SRC2"
		INNER JOIN "DIST_IO_FK2" "DIST_IO_FK2" ON  "DIST_IO_FK2"."PS_PARTKEY" = "SAT_IO_SRC2"."P_PARTKEY"
		GROUP BY  "SAT_IO_SRC2"."PART_HKEY",  "SAT_IO_SRC2"."P_PARTKEY",  "SAT_IO_SRC2"."P_NAME",  "SAT_IO_SRC2"."P_SIZE"
	)
	, "DIST_FK1" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_SRC1"."PS_SUPPKEY" AS "PS_SUPPKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_SRC1"
	)
	, "DIST_FK2" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_SRC2"."PS_PARTKEY" AS "PS_PARTKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_SRC2"
	)
	, "PREP_FIND_BK_FK1" AS 
	( 
		SELECT 
			  UPPER(REPLACE(TRIM( "SAT_SRC1"."S_NAME"),'^','\\' || '^')) AS "S_NAME_BK"
			, "DIST_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "SAT_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, 1 AS "GENERAL_ORDER"
		FROM "DIST_FK1" "DIST_FK1"
		INNER JOIN "SAT_SRC1" "SAT_SRC1" ON  "DIST_FK1"."PS_SUPPKEY" = "SAT_SRC1"."S_SUPPKEY"
		INNER JOIN {{ source('RDV', 'H_SUPPLIER') }} "HUB_SRC1" ON  "HUB_SRC1"."SUPPLIER_HKEY" = "SAT_SRC1"."SUPPLIER_HKEY"
		UNION ALL 
		SELECT 
			  "EXT_FKBK_SRC1"."S_NAME_BK" AS "S_NAME_BK"
			, "DIST_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "EXT_FKBK_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, 0 AS "GENERAL_ORDER"
		FROM "DIST_FK1" "DIST_FK1"
		INNER JOIN {{ ref('VS_DEMO_TC_EXT_SF1_SUPPLIER') }} "EXT_FKBK_SRC1" ON  "DIST_FK1"."PS_SUPPKEY" = "EXT_FKBK_SRC1"."S_SUPPKEY"
	)
	, "PREP_FIND_BK_FK2" AS 
	( 
		SELECT 
			  UPPER(REPLACE(TRIM( "SAT_SRC2"."P_NAME"),'^','\\' || '^')) AS "P_NAME_BK"
			, UPPER( TO_CHAR("SAT_SRC2"."P_SIZE")) AS "P_SIZE_BK"
			, "DIST_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
			, "SAT_SRC2"."LOAD_DATE" AS "LOAD_DATE"
			, 1 AS "GENERAL_ORDER"
		FROM "DIST_FK2" "DIST_FK2"
		INNER JOIN "SAT_SRC2" "SAT_SRC2" ON  "DIST_FK2"."PS_PARTKEY" = "SAT_SRC2"."P_PARTKEY"
		INNER JOIN {{ source('RDV', 'H_PART') }} "HUB_SRC2" ON  "HUB_SRC2"."PART_HKEY" = "SAT_SRC2"."PART_HKEY"
		UNION ALL 
		SELECT 
			  "EXT_FKBK_SRC2"."P_NAME_BK" AS "P_NAME_BK"
			, "EXT_FKBK_SRC2"."P_SIZE_BK" AS "P_SIZE_BK"
			, "DIST_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
			, "EXT_FKBK_SRC2"."LOAD_DATE" AS "LOAD_DATE"
			, 0 AS "GENERAL_ORDER"
		FROM "DIST_FK2" "DIST_FK2"
		INNER JOIN {{ ref('VS_DEMO_TC_EXT_SF1_PART') }} "EXT_FKBK_SRC2" ON  "DIST_FK2"."PS_PARTKEY" = "EXT_FKBK_SRC2"."P_PARTKEY"
	)
	, "ORDER_BK_FK1" AS 
	( 
		SELECT 
			  "PREP_FIND_BK_FK1"."S_NAME_BK" AS "S_NAME_BK"
			, "PREP_FIND_BK_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, ROW_NUMBER()OVER(PARTITION BY "PREP_FIND_BK_FK1"."PS_SUPPKEY" ORDER BY "PREP_FIND_BK_FK1"."GENERAL_ORDER",
				"PREP_FIND_BK_FK1"."LOAD_DATE" DESC) AS "DUMMY"
		FROM "PREP_FIND_BK_FK1" "PREP_FIND_BK_FK1"
	)
	, "ORDER_BK_FK2" AS 
	( 
		SELECT 
			  "PREP_FIND_BK_FK2"."P_NAME_BK" AS "P_NAME_BK"
			, "PREP_FIND_BK_FK2"."P_SIZE_BK" AS "P_SIZE_BK"
			, "PREP_FIND_BK_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
			, ROW_NUMBER()OVER(PARTITION BY "PREP_FIND_BK_FK2"."PS_PARTKEY" ORDER BY "PREP_FIND_BK_FK2"."GENERAL_ORDER",
				"PREP_FIND_BK_FK2"."LOAD_DATE" DESC) AS "DUMMY"
		FROM "PREP_FIND_BK_FK2" "PREP_FIND_BK_FK2"
	)
	, "FIND_BK_FK1" AS 
	( 
		SELECT 
			  "ORDER_BK_FK1"."S_NAME_BK" AS "S_NAME_BK"
			, "ORDER_BK_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
		FROM "ORDER_BK_FK1" "ORDER_BK_FK1"
		WHERE  "ORDER_BK_FK1"."DUMMY" = 1
	)
	, "FIND_BK_FK2" AS 
	( 
		SELECT 
			  "ORDER_BK_FK2"."P_NAME_BK" AS "P_NAME_BK"
			, "ORDER_BK_FK2"."P_SIZE_BK" AS "P_SIZE_BK"
			, "ORDER_BK_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
		FROM "ORDER_BK_FK2" "ORDER_BK_FK2"
		WHERE  "ORDER_BK_FK2"."DUMMY" = 1
	)
	, "FAKE_PREV_REF" AS 
	( 
		SELECT 
			  "STG_DL_PREV_SRC"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_PREV') }} "STG_DL_PREV_SRC"
		WHERE  0 = 1
	)
	SELECT 
		  UPPER(MD5_HEX(  'SF1' || '^' || COALESCE("FIND_BK_FK1"."S_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' || 
			'SF1' || '^' || COALESCE("FIND_BK_FK2"."P_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' ||  COALESCE("FIND_BK_FK2"."P_SIZE_BK","MEX_SRC"."KEY_ATTRIBUTE_NUMBER")|| '^'  )) AS "LND_SF1_PARTSUPP_HKEY"
		, UPPER(MD5_HEX( 'SF1' || '^' || COALESCE("FIND_BK_FK1"."S_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' )) AS "SUPPLIER_HKEY"
		, UPPER(MD5_HEX( 'SF1' || '^' || COALESCE("FIND_BK_FK2"."P_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' ||  COALESCE("FIND_BK_FK2"."P_SIZE_BK",
			"MEX_SRC"."KEY_ATTRIBUTE_NUMBER")|| '^' )) AS "PART_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, 'SF1.SF1_PARTSUPP' AS "RECORD_SOURCE"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
		, "EXT_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, TO_CHAR(NULL) AS "S_NAME_FK_PSSUPPKEY_BK"
		, TO_CHAR(NULL) AS "P_NAME_FK_PSPARTKEY_BK"
		, TO_CHAR(NULL) AS "P_SIZE_FK_PSPARTKEY_BK"
		, "EXT_SRC"."P_NAME" AS "P_NAME"
		, "EXT_SRC"."P_SIZE" AS "P_SIZE"
		, "EXT_SRC"."S_NAME" AS "S_NAME"
		, "EXT_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "EXT_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "EXT_SRC"."PS_COMMENT" AS "PS_COMMENT"
		, "EXT_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_SRC"
	INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'
	LEFT OUTER JOIN "FIND_BK_FK1" "FIND_BK_FK1" ON  "EXT_SRC"."PS_SUPPKEY" = "FIND_BK_FK1"."PS_SUPPKEY"
	LEFT OUTER JOIN "FIND_BK_FK2" "FIND_BK_FK2" ON  "EXT_SRC"."PS_PARTKEY" = "FIND_BK_FK2"."PS_PARTKEY"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "DIST_IO_FK1" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_IO_SRC1"."PS_SUPPKEY" AS "PS_SUPPKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_IO_SRC1"
	)
	, "DIST_IO_FK2" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_IO_SRC2"."PS_PARTKEY" AS "PS_PARTKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_IO_SRC2"
	)
	, "SAT_SRC1" AS 
	( 
		SELECT 
			  "SAT_IO_SRC1"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "SAT_IO_SRC1"."S_SUPPKEY" AS "S_SUPPKEY"
			, MAX("SAT_IO_SRC1"."LOAD_DATE") AS "LOAD_DATE"
			, "SAT_IO_SRC1"."S_NAME" AS "S_NAME"
		FROM "DIST_IO_FK1" "DIST_IO_FK1"
		INNER JOIN {{ source('RDV', 'S_SF1_SUPPLIER') }} "SAT_IO_SRC1" ON  "DIST_IO_FK1"."PS_SUPPKEY" = "SAT_IO_SRC1"."S_SUPPKEY"
		GROUP BY  "SAT_IO_SRC1"."SUPPLIER_HKEY",  "SAT_IO_SRC1"."S_SUPPKEY",  "SAT_IO_SRC1"."S_NAME"
	)
	, "SAT_SRC2" AS 
	( 
		SELECT 
			  "SAT_IO_SRC2"."PART_HKEY" AS "PART_HKEY"
			, "SAT_IO_SRC2"."P_PARTKEY" AS "P_PARTKEY"
			, MAX("SAT_IO_SRC2"."LOAD_DATE") AS "LOAD_DATE"
			, "SAT_IO_SRC2"."P_NAME" AS "P_NAME"
			, "SAT_IO_SRC2"."P_SIZE" AS "P_SIZE"
		FROM "DIST_IO_FK2" "DIST_IO_FK2"
		INNER JOIN {{ source('RDV', 'S_SF1_PART') }} "SAT_IO_SRC2" ON  "DIST_IO_FK2"."PS_PARTKEY" = "SAT_IO_SRC2"."P_PARTKEY"
		GROUP BY  "SAT_IO_SRC2"."PART_HKEY",  "SAT_IO_SRC2"."P_PARTKEY",  "SAT_IO_SRC2"."P_NAME",  "SAT_IO_SRC2"."P_SIZE"
	)
	, "DIST_FK1" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_SRC1"."PS_SUPPKEY" AS "PS_SUPPKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_SRC1"
	)
	, "DIST_FK2" AS 
	( 
		SELECT DISTINCT 
 			  "EXT_DIS_SRC2"."PS_PARTKEY" AS "PS_PARTKEY"
		FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_DIS_SRC2"
	)
	, "PREP_FIND_BK_FK1" AS 
	( 
		SELECT 
			  UPPER(REPLACE(TRIM( "SAT_SRC1"."S_NAME"),'^','\\' || '^')) AS "S_NAME_BK"
			, "DIST_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "SAT_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, 1 AS "GENERAL_ORDER"
		FROM "DIST_FK1" "DIST_FK1"
		INNER JOIN "SAT_SRC1" "SAT_SRC1" ON  "DIST_FK1"."PS_SUPPKEY" = "SAT_SRC1"."S_SUPPKEY"
		INNER JOIN {{ source('RDV', 'H_SUPPLIER') }} "HUB_SRC1" ON  "HUB_SRC1"."SUPPLIER_HKEY" = "SAT_SRC1"."SUPPLIER_HKEY"
		UNION ALL 
		SELECT 
			  "EXT_FKBK_SRC1"."S_NAME_BK" AS "S_NAME_BK"
			, "DIST_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "EXT_FKBK_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, 0 AS "GENERAL_ORDER"
		FROM "DIST_FK1" "DIST_FK1"
		INNER JOIN {{ ref('VS_DEMO_TC_EXT_SF1_SUPPLIER') }} "EXT_FKBK_SRC1" ON  "DIST_FK1"."PS_SUPPKEY" = "EXT_FKBK_SRC1"."S_SUPPKEY"
	)
	, "PREP_FIND_BK_FK2" AS 
	( 
		SELECT 
			  UPPER(REPLACE(TRIM( "SAT_SRC2"."P_NAME"),'^','\\' || '^')) AS "P_NAME_BK"
			, UPPER( TO_CHAR("SAT_SRC2"."P_SIZE")) AS "P_SIZE_BK"
			, "DIST_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
			, "SAT_SRC2"."LOAD_DATE" AS "LOAD_DATE"
			, 1 AS "GENERAL_ORDER"
		FROM "DIST_FK2" "DIST_FK2"
		INNER JOIN "SAT_SRC2" "SAT_SRC2" ON  "DIST_FK2"."PS_PARTKEY" = "SAT_SRC2"."P_PARTKEY"
		INNER JOIN {{ source('RDV', 'H_PART') }} "HUB_SRC2" ON  "HUB_SRC2"."PART_HKEY" = "SAT_SRC2"."PART_HKEY"
		UNION ALL 
		SELECT 
			  "EXT_FKBK_SRC2"."P_NAME_BK" AS "P_NAME_BK"
			, "EXT_FKBK_SRC2"."P_SIZE_BK" AS "P_SIZE_BK"
			, "DIST_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
			, "EXT_FKBK_SRC2"."LOAD_DATE" AS "LOAD_DATE"
			, 0 AS "GENERAL_ORDER"
		FROM "DIST_FK2" "DIST_FK2"
		INNER JOIN {{ ref('VS_DEMO_TC_EXT_SF1_PART') }} "EXT_FKBK_SRC2" ON  "DIST_FK2"."PS_PARTKEY" = "EXT_FKBK_SRC2"."P_PARTKEY"
	)
	, "ORDER_BK_FK1" AS 
	( 
		SELECT 
			  "PREP_FIND_BK_FK1"."S_NAME_BK" AS "S_NAME_BK"
			, "PREP_FIND_BK_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, ROW_NUMBER()OVER(PARTITION BY "PREP_FIND_BK_FK1"."PS_SUPPKEY" ORDER BY "PREP_FIND_BK_FK1"."GENERAL_ORDER",
				"PREP_FIND_BK_FK1"."LOAD_DATE" DESC) AS "DUMMY"
		FROM "PREP_FIND_BK_FK1" "PREP_FIND_BK_FK1"
	)
	, "ORDER_BK_FK2" AS 
	( 
		SELECT 
			  "PREP_FIND_BK_FK2"."P_NAME_BK" AS "P_NAME_BK"
			, "PREP_FIND_BK_FK2"."P_SIZE_BK" AS "P_SIZE_BK"
			, "PREP_FIND_BK_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
			, ROW_NUMBER()OVER(PARTITION BY "PREP_FIND_BK_FK2"."PS_PARTKEY" ORDER BY "PREP_FIND_BK_FK2"."GENERAL_ORDER",
				"PREP_FIND_BK_FK2"."LOAD_DATE" DESC) AS "DUMMY"
		FROM "PREP_FIND_BK_FK2" "PREP_FIND_BK_FK2"
	)
	, "FIND_BK_FK1" AS 
	( 
		SELECT 
			  "ORDER_BK_FK1"."S_NAME_BK" AS "S_NAME_BK"
			, "ORDER_BK_FK1"."PS_SUPPKEY" AS "PS_SUPPKEY"
		FROM "ORDER_BK_FK1" "ORDER_BK_FK1"
		WHERE  "ORDER_BK_FK1"."DUMMY" = 1
	)
	, "FIND_BK_FK2" AS 
	( 
		SELECT 
			  "ORDER_BK_FK2"."P_NAME_BK" AS "P_NAME_BK"
			, "ORDER_BK_FK2"."P_SIZE_BK" AS "P_SIZE_BK"
			, "ORDER_BK_FK2"."PS_PARTKEY" AS "PS_PARTKEY"
		FROM "ORDER_BK_FK2" "ORDER_BK_FK2"
		WHERE  "ORDER_BK_FK2"."DUMMY" = 1
	)
	SELECT 
		  UPPER(MD5_HEX(  'SF1' || '^' || COALESCE("FIND_BK_FK1"."S_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' || 
			'SF1' || '^' || COALESCE("FIND_BK_FK2"."P_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' ||  COALESCE("FIND_BK_FK2"."P_SIZE_BK","MEX_SRC"."KEY_ATTRIBUTE_NUMBER")|| '^'  )) AS "LND_SF1_PARTSUPP_HKEY"
		, UPPER(MD5_HEX( 'SF1' || '^' || COALESCE("FIND_BK_FK1"."S_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' )) AS "SUPPLIER_HKEY"
		, UPPER(MD5_HEX( 'SF1' || '^' || COALESCE("FIND_BK_FK2"."P_NAME_BK","MEX_SRC"."KEY_ATTRIBUTE_VARCHAR")|| '^' ||  COALESCE("FIND_BK_FK2"."P_SIZE_BK",
			"MEX_SRC"."KEY_ATTRIBUTE_NUMBER")|| '^' )) AS "PART_HKEY"
		, "EXT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, 'SF1.SF1_PARTSUPP' AS "RECORD_SOURCE"
		, "EXT_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
		, "EXT_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, TO_CHAR(NULL) AS "S_NAME_FK_PSSUPPKEY_BK"
		, TO_CHAR(NULL) AS "P_NAME_FK_PSPARTKEY_BK"
		, TO_CHAR(NULL) AS "P_SIZE_FK_PSPARTKEY_BK"
		, "EXT_SRC"."P_NAME" AS "P_NAME"
		, "EXT_SRC"."P_SIZE" AS "P_SIZE"
		, "EXT_SRC"."S_NAME" AS "S_NAME"
		, "EXT_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "EXT_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "EXT_SRC"."PS_COMMENT" AS "PS_COMMENT"
		, "EXT_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_EXT_SF1_PARTSUPP') }} "EXT_SRC"
	INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'
	LEFT OUTER JOIN "FIND_BK_FK1" "FIND_BK_FK1" ON  "EXT_SRC"."PS_SUPPKEY" = "FIND_BK_FK1"."PS_SUPPKEY"
	LEFT OUTER JOIN "FIND_BK_FK2" "FIND_BK_FK2" ON  "EXT_SRC"."PS_PARTKEY" = "FIND_BK_FK2"."PS_PARTKEY"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'