{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} DELETE  FROM {{ this }} "STG_DEL_TGT"	WHERE  NOT EXISTS	(		SELECT 			  1 AS "DUMMY"		FROM {{ source(\'VS_DEMO_TC_MTD\', \'LOAD_CYCLE_INFO\') }} "LCI_DEL_SRC"		INNER JOIN {{ source(\'VS_DEMO_TC_STG\', \'ORDER_CURR\') }} "STG_DEL_CURR_SRC" ON  "LCI_DEL_SRC"."LOAD_CYCLE_ID" = "STG_DEL_CURR_SRC"."LOAD_CYCLE_ID"	) {% endif %}'
		],
		alias='ORDER_PREV',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_SF1_ORDER_INCR']
	)
}}
select * from (
	SELECT 
		  "STG_CURR_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
		, "STG_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_SRC"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
		, "STG_CURR_SRC"."ORDER_BK" AS "ORDER_BK"
		, "STG_CURR_SRC"."C_NAME" AS "C_NAME"
		, "STG_CURR_SRC"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
		, "STG_CURR_SRC"."O_TOTALPRICE" AS "O_TOTALPRICE"
		, "STG_CURR_SRC"."O_ORDERDATE" AS "O_ORDERDATE"
		, "STG_CURR_SRC"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
		, "STG_CURR_SRC"."O_CLERK" AS "O_CLERK"
		, "STG_CURR_SRC"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
		, "STG_CURR_SRC"."O_COMMENT" AS "O_COMMENT"
		, "STG_CURR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ source('VS_DEMO_TC_STG', 'ORDER_CURR') }} "STG_CURR_SRC"
	LEFT OUTER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  "STG_CURR_SRC"."LOAD_CYCLE_ID" = "LCI_SRC"."LOAD_CYCLE_ID"
	LEFT OUTER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC_CURR_TO_PREV" ON  "MEX_SRC_CURR_TO_PREV"."LOAD_CYCLE_ID" = TO_CHAR("STG_CURR_SRC"."LOAD_CYCLE_ID" )
	WHERE  "LCI_SRC"."LOAD_CYCLE_ID" IS NULL AND "MEX_SRC_CURR_TO_PREV"."LOAD_CYCLE_ID" IS NULL

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'