{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_PARTSUPP',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_DL_SF1_SF1PARTSUPP_INIT', 'STG_DL_SF1_SF1PARTSUPP_PREP_DELETE']
	)
}}
select * from (
	SELECT 
		  "STG_DL_CURR_SRC"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
		, "STG_DL_CURR_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "STG_DL_CURR_SRC"."PART_HKEY" AS "PART_HKEY"
		, "STG_DL_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_DL_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_DL_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_DL_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_DL_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_DL_CURR_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
		, "STG_DL_CURR_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, "STG_DL_CURR_SRC"."S_NAME_FK_PSSUPPKEY_BK" AS "S_NAME_FK_PSSUPPKEY_BK"
		, "STG_DL_CURR_SRC"."P_NAME_FK_PSPARTKEY_BK" AS "P_NAME_FK_PSPARTKEY_BK"
		, "STG_DL_CURR_SRC"."P_SIZE_FK_PSPARTKEY_BK" AS "P_SIZE_FK_PSPARTKEY_BK"
		, "STG_DL_CURR_SRC"."P_NAME" AS "P_NAME"
		, "STG_DL_CURR_SRC"."P_SIZE" AS "P_SIZE"
		, "STG_DL_CURR_SRC"."S_NAME" AS "S_NAME"
		, "STG_DL_CURR_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "STG_DL_CURR_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "STG_DL_CURR_SRC"."PS_COMMENT" AS "PS_COMMENT"
		, "STG_DL_CURR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_CURR') }} "STG_DL_CURR_SRC"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_DL_CURR_PREV" AS 
	( 
		SELECT 
			  "STG_DL_CURR_INS"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
			, "STG_DL_CURR_INS"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_DL_CURR_INS"."PART_HKEY" AS "PART_HKEY"
			, "STG_DL_CURR_INS"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_DL_CURR_INS"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_DL_CURR_INS"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('I' ) AS "JRN_FLAG"
			, "STG_DL_CURR_INS"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_DL_CURR_INS"."PS_PARTKEY" AS "PS_PARTKEY"
			, "STG_DL_CURR_INS"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "STG_DL_CURR_INS"."S_NAME_FK_PSSUPPKEY_BK" AS "S_NAME_FK_PSSUPPKEY_BK"
			, "STG_DL_CURR_INS"."P_NAME_FK_PSPARTKEY_BK" AS "P_NAME_FK_PSPARTKEY_BK"
			, "STG_DL_CURR_INS"."P_SIZE_FK_PSPARTKEY_BK" AS "P_SIZE_FK_PSPARTKEY_BK"
			, "STG_DL_CURR_INS"."P_NAME" AS "P_NAME"
			, "STG_DL_CURR_INS"."P_SIZE" AS "P_SIZE"
			, "STG_DL_CURR_INS"."S_NAME" AS "S_NAME"
			, "STG_DL_CURR_INS"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "STG_DL_CURR_INS"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "STG_DL_CURR_INS"."PS_COMMENT" AS "PS_COMMENT"
			, "STG_DL_CURR_INS"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_CURR') }} "STG_DL_CURR_INS"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_PREV') }} "STG_DL_PREV_INS" ON  "STG_DL_PREV_INS"."LND_SF1_PARTSUPP_HKEY" = "STG_DL_CURR_INS"."LND_SF1_PARTSUPP_HKEY"
		WHERE  "STG_DL_PREV_INS"."LND_SF1_PARTSUPP_HKEY" IS NULL
		UNION ALL 
		SELECT 
			  "STG_DL_CURR_UPD"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
			, "STG_DL_CURR_UPD"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_DL_CURR_UPD"."PART_HKEY" AS "PART_HKEY"
			, "STG_DL_CURR_UPD"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_DL_CURR_UPD"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_DL_CURR_UPD"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('U' ) AS "JRN_FLAG"
			, "STG_DL_CURR_UPD"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_DL_CURR_UPD"."PS_PARTKEY" AS "PS_PARTKEY"
			, "STG_DL_CURR_UPD"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "STG_DL_CURR_UPD"."S_NAME_FK_PSSUPPKEY_BK" AS "S_NAME_FK_PSSUPPKEY_BK"
			, "STG_DL_CURR_UPD"."P_NAME_FK_PSPARTKEY_BK" AS "P_NAME_FK_PSPARTKEY_BK"
			, "STG_DL_CURR_UPD"."P_SIZE_FK_PSPARTKEY_BK" AS "P_SIZE_FK_PSPARTKEY_BK"
			, "STG_DL_CURR_UPD"."P_NAME" AS "P_NAME"
			, "STG_DL_CURR_UPD"."P_SIZE" AS "P_SIZE"
			, "STG_DL_CURR_UPD"."S_NAME" AS "S_NAME"
			, "STG_DL_CURR_UPD"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "STG_DL_CURR_UPD"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "STG_DL_CURR_UPD"."PS_COMMENT" AS "PS_COMMENT"
			, "STG_DL_CURR_UPD"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_CURR') }} "STG_DL_CURR_UPD"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_PREV') }} "STG_DL_PREV_UPD" ON  "STG_DL_PREV_UPD"."LND_SF1_PARTSUPP_HKEY" = "STG_DL_CURR_UPD"."LND_SF1_PARTSUPP_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_NULL" ON  "MEX_NULL"."RECORD_TYPE" = 'N'
		WHERE  COALESCE("STG_DL_PREV_UPD"."PS_PARTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_DL_CURR_UPD"."PS_PARTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_DL_PREV_UPD"."P_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."P_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_DL_PREV_UPD"."P_SIZE", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_DL_CURR_UPD"."P_SIZE", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_DL_PREV_UPD"."PS_SUPPKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_DL_CURR_UPD"."PS_SUPPKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_DL_PREV_UPD"."S_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."S_NAME", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_DL_PREV_UPD"."PS_AVAILQTY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_DL_CURR_UPD"."PS_AVAILQTY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_DL_PREV_UPD"."PS_SUPPLYCOST", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_DL_CURR_UPD"."PS_SUPPLYCOST", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_DL_PREV_UPD"."PS_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."PS_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_DL_PREV_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_DL_PREV_UPD"."SUPPLIER_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."SUPPLIER_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_DL_PREV_UPD"."PART_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_DL_CURR_UPD"."PART_HKEY", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))
		UNION ALL 
		SELECT 
			  "STG_DL_PREV_DEL"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
			, "STG_DL_PREV_DEL"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_DL_PREV_DEL"."PART_HKEY" AS "PART_HKEY"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_DL_PREV_DEL"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('D' ) AS "JRN_FLAG"
			, "STG_DL_PREV_DEL"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_DL_PREV_DEL"."PS_PARTKEY" AS "PS_PARTKEY"
			, "STG_DL_PREV_DEL"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "STG_DL_PREV_DEL"."S_NAME_FK_PSSUPPKEY_BK" AS "S_NAME_FK_PSSUPPKEY_BK"
			, "STG_DL_PREV_DEL"."P_NAME_FK_PSPARTKEY_BK" AS "P_NAME_FK_PSPARTKEY_BK"
			, "STG_DL_PREV_DEL"."P_SIZE_FK_PSPARTKEY_BK" AS "P_SIZE_FK_PSPARTKEY_BK"
			, "STG_DL_PREV_DEL"."P_NAME" AS "P_NAME"
			, "STG_DL_PREV_DEL"."P_SIZE" AS "P_SIZE"
			, "STG_DL_PREV_DEL"."S_NAME" AS "S_NAME"
			, "STG_DL_PREV_DEL"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "STG_DL_PREV_DEL"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "STG_DL_PREV_DEL"."PS_COMMENT" AS "PS_COMMENT"
			, "STG_DL_PREV_DEL"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_PREV') }} "STG_DL_PREV_DEL"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP_CURR') }} "STG_DL_CURR_DEL" ON  "STG_DL_PREV_DEL"."LND_SF1_PARTSUPP_HKEY" = "STG_DL_CURR_DEL"."LND_SF1_PARTSUPP_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		WHERE  "STG_DL_CURR_DEL"."LND_SF1_PARTSUPP_HKEY" IS NULL
	)
	SELECT 
		  "STG_DL_CURR_PREV"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
		, "STG_DL_CURR_PREV"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "STG_DL_CURR_PREV"."PART_HKEY" AS "PART_HKEY"
		, "STG_DL_CURR_PREV"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_DL_CURR_PREV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_DL_CURR_PREV"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_DL_CURR_PREV"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_DL_CURR_PREV"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_DL_CURR_PREV"."PS_PARTKEY" AS "PS_PARTKEY"
		, "STG_DL_CURR_PREV"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, "STG_DL_CURR_PREV"."S_NAME_FK_PSSUPPKEY_BK" AS "S_NAME_FK_PSSUPPKEY_BK"
		, "STG_DL_CURR_PREV"."P_NAME_FK_PSPARTKEY_BK" AS "P_NAME_FK_PSPARTKEY_BK"
		, "STG_DL_CURR_PREV"."P_SIZE_FK_PSPARTKEY_BK" AS "P_SIZE_FK_PSPARTKEY_BK"
		, "STG_DL_CURR_PREV"."P_NAME" AS "P_NAME"
		, "STG_DL_CURR_PREV"."P_SIZE" AS "P_SIZE"
		, "STG_DL_CURR_PREV"."S_NAME" AS "S_NAME"
		, "STG_DL_CURR_PREV"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "STG_DL_CURR_PREV"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "STG_DL_CURR_PREV"."PS_COMMENT" AS "PS_COMMENT"
		, "STG_DL_CURR_PREV"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "STG_DL_CURR_PREV" "STG_DL_CURR_PREV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'