{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_CUSTOMER',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'STG_SF1_SF1CUSTOMER_INIT', 'STG_SF1_SF1CUSTOMER_PREP_DELETE']
	)
}}
select * from (
	SELECT 
		  "STG_CURR_SRC"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
		, "STG_CURR_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_SRC"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_SRC"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_SRC"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_SRC"."C_CUSTKEY" AS "C_CUSTKEY"
		, "STG_CURR_SRC"."CUSTOMER_BK" AS "CUSTOMER_BK"
		, "STG_CURR_SRC"."C_NAME" AS "C_NAME"
		, "STG_CURR_SRC"."C_ADDRESS" AS "C_ADDRESS"
		, "STG_CURR_SRC"."C_NATIONKEY" AS "C_NATIONKEY"
		, "STG_CURR_SRC"."C_PHONE" AS "C_PHONE"
		, "STG_CURR_SRC"."C_ACCTBAL" AS "C_ACCTBAL"
		, "STG_CURR_SRC"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
		, "STG_CURR_SRC"."C_COMMENT" AS "C_COMMENT"
		, "STG_CURR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER_CURR') }} "STG_CURR_SRC"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_CURR_PREV" AS 
	( 
		SELECT 
			  "STG_CURR_INS"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "STG_CURR_INS"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_INS"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_INS"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_INS"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('I' ) AS "JRN_FLAG"
			, "STG_CURR_INS"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_INS"."C_CUSTKEY" AS "C_CUSTKEY"
			, "STG_CURR_INS"."CUSTOMER_BK" AS "CUSTOMER_BK"
			, "STG_CURR_INS"."C_NAME" AS "C_NAME"
			, "STG_CURR_INS"."C_ADDRESS" AS "C_ADDRESS"
			, "STG_CURR_INS"."C_NATIONKEY" AS "C_NATIONKEY"
			, "STG_CURR_INS"."C_PHONE" AS "C_PHONE"
			, "STG_CURR_INS"."C_ACCTBAL" AS "C_ACCTBAL"
			, "STG_CURR_INS"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "STG_CURR_INS"."C_COMMENT" AS "C_COMMENT"
			, "STG_CURR_INS"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER_CURR') }} "STG_CURR_INS"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER_PREV') }} "STG_PREV_INS" ON  "STG_PREV_INS"."CUSTOMER_HKEY" = "STG_CURR_INS"."CUSTOMER_HKEY"
		WHERE  "STG_PREV_INS"."CUSTOMER_HKEY" IS NULL
		UNION ALL 
		SELECT 
			  "STG_CURR_UPD"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "STG_CURR_UPD"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_CURR_UPD"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_CURR_UPD"."SRC_BK" AS "SRC_BK"
			, "STG_CURR_UPD"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('U' ) AS "JRN_FLAG"
			, "STG_CURR_UPD"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_CURR_UPD"."C_CUSTKEY" AS "C_CUSTKEY"
			, "STG_CURR_UPD"."CUSTOMER_BK" AS "CUSTOMER_BK"
			, "STG_CURR_UPD"."C_NAME" AS "C_NAME"
			, "STG_CURR_UPD"."C_ADDRESS" AS "C_ADDRESS"
			, "STG_CURR_UPD"."C_NATIONKEY" AS "C_NATIONKEY"
			, "STG_CURR_UPD"."C_PHONE" AS "C_PHONE"
			, "STG_CURR_UPD"."C_ACCTBAL" AS "C_ACCTBAL"
			, "STG_CURR_UPD"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "STG_CURR_UPD"."C_COMMENT" AS "C_COMMENT"
			, "STG_CURR_UPD"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER_CURR') }} "STG_CURR_UPD"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER_PREV') }} "STG_PREV_UPD" ON  "STG_PREV_UPD"."CUSTOMER_HKEY" = "STG_CURR_UPD"."CUSTOMER_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_NULL" ON  "MEX_NULL"."RECORD_TYPE" = 'N'
		WHERE  COALESCE("STG_PREV_UPD"."C_CUSTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."C_CUSTKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."C_ADDRESS", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."C_ADDRESS", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."C_NATIONKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."C_NATIONKEY", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."C_PHONE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."C_PHONE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."C_ACCTBAL", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER))!= COALESCE("STG_CURR_UPD"."C_ACCTBAL", CAST("MEX_NULL"."ATTRIBUTE_NUMBER" AS NUMBER)) OR  COALESCE("STG_PREV_UPD"."C_MKTSEGMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."C_MKTSEGMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."C_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."C_COMMENT", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR)) OR  COALESCE("STG_PREV_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))!= COALESCE("STG_CURR_UPD"."DSS_RECORD_SOURCE", CAST("MEX_NULL"."ATTRIBUTE_VARCHAR" AS VARCHAR))
		UNION ALL 
		SELECT 
			  "STG_PREV_DEL"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "STG_PREV_DEL"."SRC_BK" AS "SRC_BK"
			, "STG_PREV_DEL"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, TO_CHAR('D' ) AS "JRN_FLAG"
			, "STG_PREV_DEL"."RECORD_TYPE" AS "RECORD_TYPE"
			, "STG_PREV_DEL"."C_CUSTKEY" AS "C_CUSTKEY"
			, "STG_PREV_DEL"."CUSTOMER_BK" AS "CUSTOMER_BK"
			, "STG_PREV_DEL"."C_NAME" AS "C_NAME"
			, "STG_PREV_DEL"."C_ADDRESS" AS "C_ADDRESS"
			, "STG_PREV_DEL"."C_NATIONKEY" AS "C_NATIONKEY"
			, "STG_PREV_DEL"."C_PHONE" AS "C_PHONE"
			, "STG_PREV_DEL"."C_ACCTBAL" AS "C_ACCTBAL"
			, "STG_PREV_DEL"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "STG_PREV_DEL"."C_COMMENT" AS "C_COMMENT"
			, "STG_PREV_DEL"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER_PREV') }} "STG_PREV_DEL"
		LEFT OUTER JOIN {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER_CURR') }} "STG_CURR_DEL" ON  "STG_PREV_DEL"."CUSTOMER_HKEY" = "STG_CURR_DEL"."CUSTOMER_HKEY"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		WHERE  "STG_CURR_DEL"."CUSTOMER_HKEY" IS NULL
	)
	SELECT 
		  "STG_CURR_PREV"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
		, "STG_CURR_PREV"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_CURR_PREV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_CURR_PREV"."SRC_BK" AS "SRC_BK"
		, "STG_CURR_PREV"."RECORD_SOURCE" AS "RECORD_SOURCE"
		, "STG_CURR_PREV"."JRN_FLAG" AS "JRN_FLAG"
		, "STG_CURR_PREV"."RECORD_TYPE" AS "RECORD_TYPE"
		, "STG_CURR_PREV"."C_CUSTKEY" AS "C_CUSTKEY"
		, "STG_CURR_PREV"."CUSTOMER_BK" AS "CUSTOMER_BK"
		, "STG_CURR_PREV"."C_NAME" AS "C_NAME"
		, "STG_CURR_PREV"."C_ADDRESS" AS "C_ADDRESS"
		, "STG_CURR_PREV"."C_NATIONKEY" AS "C_NATIONKEY"
		, "STG_CURR_PREV"."C_PHONE" AS "C_PHONE"
		, "STG_CURR_PREV"."C_ACCTBAL" AS "C_ACCTBAL"
		, "STG_CURR_PREV"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
		, "STG_CURR_PREV"."C_COMMENT" AS "C_COMMENT"
		, "STG_CURR_PREV"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "STG_CURR_PREV" "STG_CURR_PREV"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'