{{
	config(
		materialized='view',
		alias='VW_ORDER',
		schema='VS_DEMO_TC_DFV',
		tags=['view', 'VS_DEMO_TC', 'SRC_SF1_ORDER_TDFV_INCR']
	)
}}
	WITH "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
			, "CDC_SRC"."C_NAME" AS "C_NAME"
			, "CDC_SRC"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
			, "CDC_SRC"."O_TOTALPRICE" AS "O_TOTALPRICE"
			, "CDC_SRC"."O_ORDERDATE" AS "O_ORDERDATE"
			, "CDC_SRC"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
			, "CDC_SRC"."O_CLERK" AS "O_CLERK"
			, "CDC_SRC"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
			, "CDC_SRC"."O_COMMENT" AS "O_COMMENT"
			, "CDC_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('PG2_SOURCE_DATA_TC"."TPCH_SF1', 'SF1_ORDERS') }} "CDC_SRC"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."O_ORDERKEY" AS "O_ORDERKEY"
			, "DELTA_VIEW_FILTER"."C_NAME" AS "C_NAME"
			, "DELTA_VIEW_FILTER"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
			, "DELTA_VIEW_FILTER"."O_TOTALPRICE" AS "O_TOTALPRICE"
			, "DELTA_VIEW_FILTER"."O_ORDERDATE" AS "O_ORDERDATE"
			, "DELTA_VIEW_FILTER"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
			, "DELTA_VIEW_FILTER"."O_CLERK" AS "O_CLERK"
			, "DELTA_VIEW_FILTER"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
			, "DELTA_VIEW_FILTER"."O_COMMENT" AS "O_COMMENT"
			, "DELTA_VIEW_FILTER"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."O_ORDERKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "O_ORDERKEY"
			, "DELTA_VIEW"."C_NAME" AS "C_NAME"
			, "DELTA_VIEW"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
			, "DELTA_VIEW"."O_TOTALPRICE" AS "O_TOTALPRICE"
			, "DELTA_VIEW"."O_ORDERDATE" AS "O_ORDERDATE"
			, "DELTA_VIEW"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
			, "DELTA_VIEW"."O_CLERK" AS "O_CLERK"
			, "DELTA_VIEW"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
			, "DELTA_VIEW"."O_COMMENT" AS "O_COMMENT"
			, "DELTA_VIEW"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."O_ORDERKEY" AS "O_ORDERKEY"
		, "PREPJOINBK"."C_NAME" AS "C_NAME"
		, "PREPJOINBK"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
		, "PREPJOINBK"."O_TOTALPRICE" AS "O_TOTALPRICE"
		, "PREPJOINBK"."O_ORDERDATE" AS "O_ORDERDATE"
		, "PREPJOINBK"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
		, "PREPJOINBK"."O_CLERK" AS "O_CLERK"
		, "PREPJOINBK"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
		, "PREPJOINBK"."O_COMMENT" AS "O_COMMENT"
		, "PREPJOINBK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "PREPJOINBK" "PREPJOINBK"
