{{
	config(
		materialized='view',
		alias='VW_SF1_PART',
		schema='VS_DEMO_TC_DFV',
		tags=['view', 'VS_DEMO_TC', 'SRC_SF1_SF1PART_TDFV_INCR']
	)
}}
	WITH "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."P_PARTKEY" AS "P_PARTKEY"
			, "CDC_SRC"."P_NAME" AS "P_NAME"
			, "CDC_SRC"."P_SIZE" AS "P_SIZE"
			, "CDC_SRC"."P_MFGR" AS "P_MFGR"
			, "CDC_SRC"."P_BRAND" AS "P_BRAND"
			, "CDC_SRC"."P_TYPE" AS "P_TYPE"
			, "CDC_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "CDC_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "CDC_SRC"."P_COMMENT" AS "P_COMMENT"
			, "CDC_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('PG2_SOURCE_DATA_TC"."TPCH_SF1', 'SF1_PART') }} "CDC_SRC"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."P_PARTKEY" AS "P_PARTKEY"
			, "DELTA_VIEW_FILTER"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW_FILTER"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW_FILTER"."P_MFGR" AS "P_MFGR"
			, "DELTA_VIEW_FILTER"."P_BRAND" AS "P_BRAND"
			, "DELTA_VIEW_FILTER"."P_TYPE" AS "P_TYPE"
			, "DELTA_VIEW_FILTER"."P_CONTAINER" AS "P_CONTAINER"
			, "DELTA_VIEW_FILTER"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "DELTA_VIEW_FILTER"."P_COMMENT" AS "P_COMMENT"
			, "DELTA_VIEW_FILTER"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."P_PARTKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "P_PARTKEY"
			, "DELTA_VIEW"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW"."P_MFGR" AS "P_MFGR"
			, "DELTA_VIEW"."P_BRAND" AS "P_BRAND"
			, "DELTA_VIEW"."P_TYPE" AS "P_TYPE"
			, "DELTA_VIEW"."P_CONTAINER" AS "P_CONTAINER"
			, "DELTA_VIEW"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "DELTA_VIEW"."P_COMMENT" AS "P_COMMENT"
			, "DELTA_VIEW"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."P_PARTKEY" AS "P_PARTKEY"
		, "PREPJOINBK"."P_NAME" AS "P_NAME"
		, "PREPJOINBK"."P_SIZE" AS "P_SIZE"
		, "PREPJOINBK"."P_MFGR" AS "P_MFGR"
		, "PREPJOINBK"."P_BRAND" AS "P_BRAND"
		, "PREPJOINBK"."P_TYPE" AS "P_TYPE"
		, "PREPJOINBK"."P_CONTAINER" AS "P_CONTAINER"
		, "PREPJOINBK"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "PREPJOINBK"."P_COMMENT" AS "P_COMMENT"
		, "PREPJOINBK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "PREPJOINBK" "PREPJOINBK"
