{{
	config(
		materialized='view',
		alias='VW_SF1_SUPPLIER',
		schema='VS_DEMO_TC_DFV',
		tags=['view', 'VS_DEMO_TC', 'SRC_SF1_SF1SUPPLIER_TDFV_INCR']
	)
}}
	WITH "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."S_SUPPKEY" AS "S_SUPPKEY"
			, "CDC_SRC"."S_NAME" AS "S_NAME"
			, "CDC_SRC"."S_ADDRESS" AS "S_ADDRESS"
			, "CDC_SRC"."S_NATIONKEY" AS "S_NATIONKEY"
			, "CDC_SRC"."S_PHONE" AS "S_PHONE"
			, "CDC_SRC"."S_ACCTBAL" AS "S_ACCTBAL"
			, "CDC_SRC"."S_COMMENT" AS "S_COMMENT"
			, "CDC_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('PG2_SOURCE_DATA_TC"."TPCH_SF1', 'SF1_SUPPLIER') }} "CDC_SRC"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."S_SUPPKEY" AS "S_SUPPKEY"
			, "DELTA_VIEW_FILTER"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW_FILTER"."S_ADDRESS" AS "S_ADDRESS"
			, "DELTA_VIEW_FILTER"."S_NATIONKEY" AS "S_NATIONKEY"
			, "DELTA_VIEW_FILTER"."S_PHONE" AS "S_PHONE"
			, "DELTA_VIEW_FILTER"."S_ACCTBAL" AS "S_ACCTBAL"
			, "DELTA_VIEW_FILTER"."S_COMMENT" AS "S_COMMENT"
			, "DELTA_VIEW_FILTER"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."S_SUPPKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "S_SUPPKEY"
			, "DELTA_VIEW"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW"."S_ADDRESS" AS "S_ADDRESS"
			, "DELTA_VIEW"."S_NATIONKEY" AS "S_NATIONKEY"
			, "DELTA_VIEW"."S_PHONE" AS "S_PHONE"
			, "DELTA_VIEW"."S_ACCTBAL" AS "S_ACCTBAL"
			, "DELTA_VIEW"."S_COMMENT" AS "S_COMMENT"
			, "DELTA_VIEW"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."S_SUPPKEY" AS "S_SUPPKEY"
		, "PREPJOINBK"."S_NAME" AS "S_NAME"
		, "PREPJOINBK"."S_ADDRESS" AS "S_ADDRESS"
		, "PREPJOINBK"."S_NATIONKEY" AS "S_NATIONKEY"
		, "PREPJOINBK"."S_PHONE" AS "S_PHONE"
		, "PREPJOINBK"."S_ACCTBAL" AS "S_ACCTBAL"
		, "PREPJOINBK"."S_COMMENT" AS "S_COMMENT"
		, "PREPJOINBK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "PREPJOINBK" "PREPJOINBK"
