{{
	config(
		materialized='view',
		alias='VW_SF1_LINEITEM',
		schema='VS_DEMO_TC_DFV',
		tags=['view', 'VS_DEMO_TC', 'SRC_SF1_SF1LINEITEM_TDFV_INCR']
	)
}}
	WITH "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."L_ORDERKEY" AS "L_ORDERKEY"
			, "CDC_SRC"."L_LINENUMBER" AS "L_LINENUMBER"
			, "CDC_SRC"."L_PARTKEY" AS "L_PARTKEY"
			, "CDC_SRC"."L_SUPPKEY" AS "L_SUPPKEY"
			, "CDC_SRC"."P_NAME" AS "P_NAME"
			, "CDC_SRC"."P_SIZE" AS "P_SIZE"
			, "CDC_SRC"."S_NAME" AS "S_NAME"
			, "CDC_SRC"."L_QUANTITY" AS "L_QUANTITY"
			, "CDC_SRC"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "CDC_SRC"."L_DISCOUNT" AS "L_DISCOUNT"
			, "CDC_SRC"."L_TAX" AS "L_TAX"
			, "CDC_SRC"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "CDC_SRC"."L_LINESTATUS" AS "L_LINESTATUS"
			, "CDC_SRC"."L_SHIPDATE" AS "L_SHIPDATE"
			, "CDC_SRC"."L_COMMITDATE" AS "L_COMMITDATE"
			, "CDC_SRC"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "CDC_SRC"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "CDC_SRC"."L_SHIPMODE" AS "L_SHIPMODE"
			, "CDC_SRC"."L_COMMENT" AS "L_COMMENT"
			, "CDC_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('PG2_SOURCE_DATA_TC"."TPCH_SF1', 'SF1_LINEITEM') }} "CDC_SRC"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."L_ORDERKEY" AS "L_ORDERKEY"
			, "DELTA_VIEW_FILTER"."L_LINENUMBER" AS "L_LINENUMBER"
			, "DELTA_VIEW_FILTER"."L_PARTKEY" AS "L_PARTKEY"
			, "DELTA_VIEW_FILTER"."L_SUPPKEY" AS "L_SUPPKEY"
			, "DELTA_VIEW_FILTER"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW_FILTER"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW_FILTER"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW_FILTER"."L_QUANTITY" AS "L_QUANTITY"
			, "DELTA_VIEW_FILTER"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "DELTA_VIEW_FILTER"."L_DISCOUNT" AS "L_DISCOUNT"
			, "DELTA_VIEW_FILTER"."L_TAX" AS "L_TAX"
			, "DELTA_VIEW_FILTER"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "DELTA_VIEW_FILTER"."L_LINESTATUS" AS "L_LINESTATUS"
			, "DELTA_VIEW_FILTER"."L_SHIPDATE" AS "L_SHIPDATE"
			, "DELTA_VIEW_FILTER"."L_COMMITDATE" AS "L_COMMITDATE"
			, "DELTA_VIEW_FILTER"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "DELTA_VIEW_FILTER"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "DELTA_VIEW_FILTER"."L_SHIPMODE" AS "L_SHIPMODE"
			, "DELTA_VIEW_FILTER"."L_COMMENT" AS "L_COMMENT"
			, "DELTA_VIEW_FILTER"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."L_ORDERKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_ORDERKEY"
			, COALESCE("DELTA_VIEW"."L_LINENUMBER", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_LINENUMBER"
			, COALESCE("DELTA_VIEW"."L_PARTKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_PARTKEY"
			, COALESCE("DELTA_VIEW"."L_SUPPKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_SUPPKEY"
			, "DELTA_VIEW"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW"."L_QUANTITY" AS "L_QUANTITY"
			, "DELTA_VIEW"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "DELTA_VIEW"."L_DISCOUNT" AS "L_DISCOUNT"
			, "DELTA_VIEW"."L_TAX" AS "L_TAX"
			, "DELTA_VIEW"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "DELTA_VIEW"."L_LINESTATUS" AS "L_LINESTATUS"
			, "DELTA_VIEW"."L_SHIPDATE" AS "L_SHIPDATE"
			, "DELTA_VIEW"."L_COMMITDATE" AS "L_COMMITDATE"
			, "DELTA_VIEW"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "DELTA_VIEW"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "DELTA_VIEW"."L_SHIPMODE" AS "L_SHIPMODE"
			, "DELTA_VIEW"."L_COMMENT" AS "L_COMMENT"
			, "DELTA_VIEW"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."L_ORDERKEY" AS "L_ORDERKEY"
		, "PREPJOINBK"."L_LINENUMBER" AS "L_LINENUMBER"
		, "PREPJOINBK"."L_PARTKEY" AS "L_PARTKEY"
		, "PREPJOINBK"."L_SUPPKEY" AS "L_SUPPKEY"
		, "PREPJOINBK"."P_NAME" AS "P_NAME"
		, "PREPJOINBK"."P_SIZE" AS "P_SIZE"
		, "PREPJOINBK"."S_NAME" AS "S_NAME"
		, "PREPJOINBK"."L_QUANTITY" AS "L_QUANTITY"
		, "PREPJOINBK"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
		, "PREPJOINBK"."L_DISCOUNT" AS "L_DISCOUNT"
		, "PREPJOINBK"."L_TAX" AS "L_TAX"
		, "PREPJOINBK"."L_RETURNFLAG" AS "L_RETURNFLAG"
		, "PREPJOINBK"."L_LINESTATUS" AS "L_LINESTATUS"
		, "PREPJOINBK"."L_SHIPDATE" AS "L_SHIPDATE"
		, "PREPJOINBK"."L_COMMITDATE" AS "L_COMMITDATE"
		, "PREPJOINBK"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
		, "PREPJOINBK"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
		, "PREPJOINBK"."L_SHIPMODE" AS "L_SHIPMODE"
		, "PREPJOINBK"."L_COMMENT" AS "L_COMMENT"
		, "PREPJOINBK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "PREPJOINBK" "PREPJOINBK"
