{{
	config(
		materialized='view',
		alias='VW_SF1_PARTSUPP',
		schema='VS_DEMO_TC_DFV',
		tags=['view', 'VS_DEMO_TC', 'SRC_SF1_SF1PARTSUPP_TDFV_INCR']
	)
}}
	WITH "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
			, "CDC_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "CDC_SRC"."P_NAME" AS "P_NAME"
			, "CDC_SRC"."P_SIZE" AS "P_SIZE"
			, "CDC_SRC"."S_NAME" AS "S_NAME"
			, "CDC_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "CDC_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "CDC_SRC"."PS_COMMENT" AS "PS_COMMENT"
			, "CDC_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('PG2_SOURCE_DATA_TC"."TPCH_SF1', 'SF1_PARTSUPP') }} "CDC_SRC"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."PS_PARTKEY" AS "PS_PARTKEY"
			, "DELTA_VIEW_FILTER"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "DELTA_VIEW_FILTER"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW_FILTER"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW_FILTER"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW_FILTER"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "DELTA_VIEW_FILTER"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "DELTA_VIEW_FILTER"."PS_COMMENT" AS "PS_COMMENT"
			, "DELTA_VIEW_FILTER"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."PS_PARTKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "PS_PARTKEY"
			, COALESCE("DELTA_VIEW"."PS_SUPPKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "PS_SUPPKEY"
			, "DELTA_VIEW"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "DELTA_VIEW"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "DELTA_VIEW"."PS_COMMENT" AS "PS_COMMENT"
			, "DELTA_VIEW"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."PS_PARTKEY" AS "PS_PARTKEY"
		, "PREPJOINBK"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, "PREPJOINBK"."P_NAME" AS "P_NAME"
		, "PREPJOINBK"."P_SIZE" AS "P_SIZE"
		, "PREPJOINBK"."S_NAME" AS "S_NAME"
		, "PREPJOINBK"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "PREPJOINBK"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "PREPJOINBK"."PS_COMMENT" AS "PS_COMMENT"
		, "PREPJOINBK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "PREPJOINBK" "PREPJOINBK"
