{{
	config(
		materialized='view',
		alias='VW_ORDER_CUST',
		schema='VS_DEMO_TC_DFV',
		tags=['view', 'VS_DEMO_TC', 'SRC_SF1_ORDER_CUST_TDFV_INCR']
	)
}}
	WITH "DELTA_VIEW_FILTER" AS 
	( 
		SELECT DISTINCT 
			  TO_CHAR('S' ) AS "RECORD_TYPE"
			, "CDC_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
			, "CDC_SRC"."O_CUSTKEY" AS "O_CUSTKEY"
			, "CDC_SRC"."C_NAME" AS "C_NAME"
		FROM {{ source('PG2_SOURCE_DATA_TC"."TPCH_SF1', 'SF1_ORDERS') }} "CDC_SRC"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."O_ORDERKEY" AS "O_ORDERKEY"
			, "DELTA_VIEW_FILTER"."O_CUSTKEY" AS "O_CUSTKEY"
			, "DELTA_VIEW_FILTER"."C_NAME" AS "C_NAME"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."O_ORDERKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "O_ORDERKEY"
			, COALESCE("DELTA_VIEW"."O_CUSTKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "O_CUSTKEY"
			, "DELTA_VIEW"."C_NAME" AS "C_NAME"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."O_ORDERKEY" AS "O_ORDERKEY"
		, "PREPJOINBK"."O_CUSTKEY" AS "O_CUSTKEY"
		, "PREPJOINBK"."C_NAME" AS "C_NAME"
	FROM "PREPJOINBK" "PREPJOINBK"
