{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='PIT_DETAIL_ORDERCUST',
		schema='BV',
		unique_key = ['"PIT_DETAIL_ORDERCUST_HKEY"'],
		merge_update_columns = ['"S_SF1_ORDERCUST_LDS_HKEY"', '"S_SF1_ORDERCUST_LDS_LOAD_DATE"'],
		tags=['BV', 'BV_PIT_DETAIL_ORDERCUST_PIT_INCR', 'BV_PIT_DETAIL_ORDERCUST_PIT_INIT']
	)
}}
select * from (
	WITH "SNAPSHOTDATES" AS 
	( 
		SELECT 
			  "SSDV_SRC"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "SSDV_SRC"."SNAPSHOT_TIMESTAMP" AS "SNAPSHOT_TIMESTAMP"
		FROM {{ ref('BV_VIEW_PIT_DETAIL_ORDERCUST_SNAPSHOTDATES') }} "SSDV_SRC"
		INNER JOIN {{ source('DV_MTD', 'FMC_BV_LOADING_WINDOW_TABLE') }} "BVLWT_SRC" ON  1 = 1
		WHERE  "SSDV_SRC"."SNAPSHOT_TIMESTAMP" >= "BVLWT_SRC"."FMC_BEGIN_LW_TIMESTAMP"
	)
	, "SAT_SRC1" AS 
	( 
		SELECT 
			  "SAT_ED_SRC1"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "SAT_ED_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, COALESCE(LEAD("SAT_ED_SRC1"."LOAD_DATE")OVER(PARTITION BY "SAT_ED_SRC1"."LND_ORDERCUST_HKEY" ORDER BY "SAT_ED_SRC1"."LOAD_DATE")
				, TO_TIMESTAMP('31/12/9999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')) AS "LOAD_END_DATE"
			, "SAT_ED_SRC1"."DELETE_FLAG" AS "DELETE_FLAG"
		FROM {{ ref('RDV_S_SF1_ORDERCUST_LDS') }} "SAT_ED_SRC1"
	)
	, "MIV" AS 
	( 
		SELECT 
			  UPPER(MD5_HEX( TO_CHAR("HUB_SRC"."LND_ORDERCUST_HKEY") || '^' || TO_CHAR("SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP",
				 'DD/MM/YYYY HH24:MI:SS.FF') )) AS "PIT_DETAIL_ORDERCUST_HKEY"
			, "HUB_SRC"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP" AS "SNAPSHOT_TIMESTAMP"
			, "BVLCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, COALESCE("SAT_SRC1"."LND_ORDERCUST_HKEY","UNSAT_SRC1"."LND_ORDERCUST_HKEY") AS "S_SF1_ORDERCUST_LDS_HKEY"
			, COALESCE("SAT_SRC1"."LOAD_DATE","UNSAT_SRC1"."LOAD_DATE") AS "S_SF1_ORDERCUST_LDS_LOAD_DATE"
		FROM {{ ref('RDV_L_ORDERCUST_LND') }} "HUB_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'
		INNER JOIN {{ source('DV_MTD', 'LOAD_CYCLE_INFO') }} "BVLCI_SRC" ON  1 = 1
		INNER JOIN "SNAPSHOTDATES" "SNAPSHOTDATES" ON  "SNAPSHOTDATES"."LND_ORDERCUST_HKEY" = "HUB_SRC"."LND_ORDERCUST_HKEY"
		LEFT OUTER JOIN "SAT_SRC1" "SAT_SRC1" ON  "HUB_SRC"."LND_ORDERCUST_HKEY" = "SAT_SRC1"."LND_ORDERCUST_HKEY" AND "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP" >= 
			"SAT_SRC1"."LOAD_DATE" AND "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP" < "SAT_SRC1"."LOAD_END_DATE" AND "SAT_SRC1"."DELETE_FLAG" != CAST('Y' AS VARCHAR)
		INNER JOIN {{ ref('RDV_S_SF1_ORDERCUST_LDS') }} "UNSAT_SRC1" ON  "MEX_SRC"."LOAD_CYCLE_ID"::integer = "UNSAT_SRC1"."LOAD_CYCLE_ID"
		WHERE  COALESCE("SAT_SRC1"."LOAD_DATE","UNSAT_SRC1"."LOAD_DATE")<= "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP"
	)
	, "DATA_SRC" AS 
	( 
		SELECT 
			  "MIV"."PIT_DETAIL_ORDERCUST_HKEY" AS "PIT_DETAIL_ORDERCUST_HKEY"
			, "MIV"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "MIV"."SNAPSHOT_TIMESTAMP" AS "SNAPSHOT_TIMESTAMP"
			, "MIV"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "MIV"."S_SF1_ORDERCUST_LDS_HKEY" AS "S_SF1_ORDERCUST_LDS_HKEY"
			, "MIV"."S_SF1_ORDERCUST_LDS_LOAD_DATE" AS "S_SF1_ORDERCUST_LDS_LOAD_DATE"
		FROM "MIV" "MIV"
		LEFT OUTER JOIN {{ this }} "PIT_SRC" ON  "MIV"."PIT_DETAIL_ORDERCUST_HKEY" = "PIT_SRC"."PIT_DETAIL_ORDERCUST_HKEY" AND "MIV"."S_SF1_ORDERCUST_LDS_HKEY" =
			 "PIT_SRC"."S_SF1_ORDERCUST_LDS_HKEY" AND "MIV"."S_SF1_ORDERCUST_LDS_LOAD_DATE" = "PIT_SRC"."S_SF1_ORDERCUST_LDS_LOAD_DATE"
		WHERE  "PIT_SRC"."PIT_DETAIL_ORDERCUST_HKEY" IS NULL
	)
	SELECT 
		  "DATA_SRC"."PIT_DETAIL_ORDERCUST_HKEY"
		, "DATA_SRC"."LND_ORDERCUST_HKEY"
		, "DATA_SRC"."SNAPSHOT_TIMESTAMP"
		, "DATA_SRC"."LOAD_CYCLE_ID"
		, "DATA_SRC"."S_SF1_ORDERCUST_LDS_HKEY"
		, "DATA_SRC"."S_SF1_ORDERCUST_LDS_LOAD_DATE"
	FROM "DATA_SRC"

) final 
where '{{ var("load_type") }}' = 'INCR'

UNION ALL

select * from (
	WITH "SAT_SRC1" AS 
	( 
		SELECT 
			  "SAT_ED_SRC1"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
			, "SAT_ED_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, COALESCE(LEAD("SAT_ED_SRC1"."LOAD_DATE")OVER(PARTITION BY "SAT_ED_SRC1"."LND_ORDERCUST_HKEY" ORDER BY "SAT_ED_SRC1"."LOAD_DATE")
				, TO_TIMESTAMP('31/12/9999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')) AS "LOAD_END_DATE"
			, "SAT_ED_SRC1"."DELETE_FLAG" AS "DELETE_FLAG"
		FROM {{ ref('RDV_S_SF1_ORDERCUST_LDS') }} "SAT_ED_SRC1"
	)
	SELECT 
		  UPPER(MD5_HEX( TO_CHAR("HUB_SRC"."LND_ORDERCUST_HKEY") || '^' || TO_CHAR("SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP",
			 'DD/MM/YYYY HH24:MI:SS.FF') )) AS "PIT_DETAIL_ORDERCUST_HKEY"
		, "HUB_SRC"."LND_ORDERCUST_HKEY" AS "LND_ORDERCUST_HKEY"
		, "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP" AS "SNAPSHOT_TIMESTAMP"
		, "BVLCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, COALESCE("SAT_SRC1"."LND_ORDERCUST_HKEY","UNSAT_SRC1"."LND_ORDERCUST_HKEY") AS "S_SF1_ORDERCUST_LDS_HKEY"
		, COALESCE("SAT_SRC1"."LOAD_DATE","UNSAT_SRC1"."LOAD_DATE") AS "S_SF1_ORDERCUST_LDS_LOAD_DATE"
	FROM {{ ref('RDV_L_ORDERCUST_LND') }} "HUB_SRC"
	INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  "MEX_SRC"."RECORD_TYPE" = 'U'
	INNER JOIN {{ source('DV_MTD', 'LOAD_CYCLE_INFO') }} "BVLCI_SRC" ON  1 = 1
	INNER JOIN {{ ref('BV_VIEW_PIT_DETAIL_ORDERCUST_SNAPSHOTDATES') }} "SNAPSHOTDATES" ON  "SNAPSHOTDATES"."LND_ORDERCUST_HKEY" = "HUB_SRC"."LND_ORDERCUST_HKEY"
	LEFT OUTER JOIN "SAT_SRC1" "SAT_SRC1" ON  "HUB_SRC"."LND_ORDERCUST_HKEY" = "SAT_SRC1"."LND_ORDERCUST_HKEY" AND "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP" >= 
		"SAT_SRC1"."LOAD_DATE" AND "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP" < "SAT_SRC1"."LOAD_END_DATE" AND "SAT_SRC1"."DELETE_FLAG" != CAST('Y' AS VARCHAR)
	INNER JOIN {{ ref('RDV_S_SF1_ORDERCUST_LDS') }} "UNSAT_SRC1" ON  "MEX_SRC"."LOAD_CYCLE_ID"::integer = "UNSAT_SRC1"."LOAD_CYCLE_ID"
	WHERE  COALESCE("SAT_SRC1"."LOAD_DATE","UNSAT_SRC1"."LOAD_DATE")<= "SNAPSHOTDATES"."SNAPSHOT_TIMESTAMP"

) final 
where '{{ var("load_type") }}' = 'INIT'