{{
	config(
		materialized='view',
		alias='VIEW_PIT_DETAIL_TRANS_PART_SNAPSHOTDATES',
		schema='BV',
		tags=['view', 'BV', 'BV_VIEW_PIT_DETAIL_TRANS_PART_SNAPSHOTDATES_SSD_VIEW']
	)
}}
	SELECT DISTINCT 
		  "SAT_SRC1"."PART_HKEY" AS "PART_HKEY"
		, "SAT_SRC1"."LOAD_DATE" AS "SNAPSHOT_TIMESTAMP"
	FROM {{ ref('RDV_S_SF1_PART') }} "SAT_SRC1"
