{{
	config(
		materialized='view',
		alias='VIEW_PIT_DETAIL_SUPPLIER_SNAPSHOTDATES',
		schema='BV',
		tags=['view', 'BV', 'BV_VIEW_PIT_DETAIL_SUPPLIER_SNAPSHOTDATES_SSD_VIEW']
	)
}}
	SELECT DISTINCT 
		  "SAT_SRC1"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "SAT_SRC1"."LOAD_DATE" AS "SNAPSHOT_TIMESTAMP"
	FROM {{ ref('RDV_S_SF1_SUPPLIER') }} "SAT_SRC1"
