{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='S_SF1_ORDER',
		schema='RDV',
		tags=['VS_DEMO_TC', 'SAT_SF1_ORDER_INCR', 'SAT_SF1_ORDER_INIT']
	)
}}
select * from (
	SELECT 
		  "SAT_TEMP_SRC_INUR"."ORDER_HKEY" AS "ORDER_HKEY"
		, "SAT_TEMP_SRC_INUR"."LOAD_DATE" AS "LOAD_DATE"
		, "SAT_TEMP_SRC_INUR"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "SAT_TEMP_SRC_INUR"."HASH_DIFF" AS "HASH_DIFF"
		, "SAT_TEMP_SRC_INUR"."DELETE_FLAG" AS "DELETE_FLAG"
		, "SAT_TEMP_SRC_INUR"."O_ORDERKEY" AS "O_ORDERKEY"
		, "SAT_TEMP_SRC_INUR"."C_NAME" AS "C_NAME"
		, "SAT_TEMP_SRC_INUR"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
		, "SAT_TEMP_SRC_INUR"."O_TOTALPRICE" AS "O_TOTALPRICE"
		, "SAT_TEMP_SRC_INUR"."O_ORDERDATE" AS "O_ORDERDATE"
		, "SAT_TEMP_SRC_INUR"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
		, "SAT_TEMP_SRC_INUR"."O_CLERK" AS "O_CLERK"
		, "SAT_TEMP_SRC_INUR"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
		, "SAT_TEMP_SRC_INUR"."O_COMMENT" AS "O_COMMENT"
		, "SAT_TEMP_SRC_INUR"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_STG_S_SF1_ORDER_TMP') }} "SAT_TEMP_SRC_INUR"
	WHERE  "SAT_TEMP_SRC_INUR"."SOURCE" = 'STG' AND "SAT_TEMP_SRC_INUR"."EQUAL" = 0

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_SRC" AS 
	( 
		SELECT 
			  "STG_INR_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
			, "STG_INR_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_INR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_INR_SRC"."C_NAME"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_INR_SRC"."O_ORDERSTATUS")
				,'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."O_TOTALPRICE")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."O_ORDERDATE", 'DD/MM/YYYY')),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_INR_SRC"."O_ORDERPRIORITY"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_INR_SRC"."O_CLERK"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_INR_SRC"."O_SHIPPRIORITY")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_INR_SRC"."O_COMMENT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_INR_SRC"."DSS_RECORD_SOURCE"),'~'),'^','\\' || '^')|| '^','^' || '~'),'~') )) AS "HASH_DIFF"
			, CAST('N' AS VARCHAR) AS "DELETE_FLAG"
			, "STG_INR_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
			, "STG_INR_SRC"."C_NAME" AS "C_NAME"
			, "STG_INR_SRC"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
			, "STG_INR_SRC"."O_TOTALPRICE" AS "O_TOTALPRICE"
			, "STG_INR_SRC"."O_ORDERDATE" AS "O_ORDERDATE"
			, "STG_INR_SRC"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
			, "STG_INR_SRC"."O_CLERK" AS "O_CLERK"
			, "STG_INR_SRC"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
			, "STG_INR_SRC"."O_COMMENT" AS "O_COMMENT"
			, "STG_INR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
			, ROW_NUMBER()OVER(PARTITION BY "STG_INR_SRC"."ORDER_HKEY" ORDER BY "STG_INR_SRC"."LOAD_DATE") AS "DUMMY"
		FROM {{ ref('VS_DEMO_TC_STG_ORDER') }} "STG_INR_SRC"
	)
	SELECT 
		  "STG_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
		, "STG_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "STG_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
		, "STG_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
		, "STG_SRC"."C_NAME" AS "C_NAME"
		, "STG_SRC"."O_ORDERSTATUS" AS "O_ORDERSTATUS"
		, "STG_SRC"."O_TOTALPRICE" AS "O_TOTALPRICE"
		, "STG_SRC"."O_ORDERDATE" AS "O_ORDERDATE"
		, "STG_SRC"."O_ORDERPRIORITY" AS "O_ORDERPRIORITY"
		, "STG_SRC"."O_CLERK" AS "O_CLERK"
		, "STG_SRC"."O_SHIPPRIORITY" AS "O_SHIPPRIORITY"
		, "STG_SRC"."O_COMMENT" AS "O_COMMENT"
		, "STG_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "STG_SRC" "STG_SRC"
	WHERE  "STG_SRC"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'