{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='H_SUPPLIER',
		schema='RDV',
		tags=['VS_DEMO_TC', 'HUB_SF1_SUPPLIER_INCR', 'HUB_SF1_SUPPLIER_INIT']
	)
}}
select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."SUPPLIER_BK" AS "SUPPLIER_BK"
			, "STG_SRC1"."SRC_BK" AS "SRC_BK"
			, "STG_SRC1"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER') }} "STG_SRC1"
		WHERE  "STG_SRC1"."RECORD_TYPE" = 'S'
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."SUPPLIER_BK" AS "SUPPLIER_BK"
			, "CHANGE_SET"."SRC_BK" AS "SRC_BK"
			, "CHANGE_SET"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."SUPPLIER_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER",
				"CHANGE_SET"."LOAD_DATE","CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	SELECT 
		  "MIN_LOAD_TIME"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
		, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "MIN_LOAD_TIME"."SUPPLIER_BK" AS "SUPPLIER_BK"
		, "MIN_LOAD_TIME"."SRC_BK" AS "SRC_BK"
		, "MIN_LOAD_TIME"."RECORD_SOURCE" AS "RECORD_SOURCE"
	FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
	LEFT OUTER JOIN {{ this }} "HUB_SRC" ON  "MIN_LOAD_TIME"."SUPPLIER_HKEY" = "HUB_SRC"."SUPPLIER_HKEY"
	WHERE  "MIN_LOAD_TIME"."DUMMY" = 1 AND "HUB_SRC"."SUPPLIER_HKEY" is NULL

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "CHANGE_SET" AS 
	( 
		SELECT 
			  "STG_SRC1"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_SRC1"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_SRC1"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, 0 AS "LOGPOSITION"
			, "STG_SRC1"."SUPPLIER_BK" AS "SUPPLIER_BK"
			, "STG_SRC1"."SRC_BK" AS "SRC_BK"
			, "STG_SRC1"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, 0 AS "GENERAL_ORDER"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_SUPPLIER') }} "STG_SRC1"
	)
	, "MIN_LOAD_TIME" AS 
	( 
		SELECT 
			  "CHANGE_SET"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "CHANGE_SET"."LOAD_DATE" AS "LOAD_DATE"
			, "CHANGE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CHANGE_SET"."SUPPLIER_BK" AS "SUPPLIER_BK"
			, "CHANGE_SET"."SRC_BK" AS "SRC_BK"
			, "CHANGE_SET"."RECORD_SOURCE" AS "RECORD_SOURCE"
			, ROW_NUMBER()OVER(PARTITION BY "CHANGE_SET"."SUPPLIER_HKEY" ORDER BY "CHANGE_SET"."GENERAL_ORDER",
				"CHANGE_SET"."LOAD_DATE","CHANGE_SET"."LOGPOSITION") AS "DUMMY"
		FROM "CHANGE_SET" "CHANGE_SET"
	)
	SELECT 
		  "MIN_LOAD_TIME"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "MIN_LOAD_TIME"."LOAD_DATE" AS "LOAD_DATE"
		, "MIN_LOAD_TIME"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "MIN_LOAD_TIME"."SUPPLIER_BK" AS "SUPPLIER_BK"
		, "MIN_LOAD_TIME"."SRC_BK" AS "SRC_BK"
		, "MIN_LOAD_TIME"."RECORD_SOURCE" AS "RECORD_SOURCE"
	FROM "MIN_LOAD_TIME" "MIN_LOAD_TIME"
	WHERE  "MIN_LOAD_TIME"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'