{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='S_SF1_SF1_PARTSUPP_LDS',
		schema='RDV',
		tags=['VS_DEMO_TC', 'LDS_SF1_SF1PARTSUPP_INCR', 'LDS_SF1_SF1PARTSUPP_INIT']
	)
}}
select * from (
	SELECT 
		  "LDS_TEMP_SRC_INUR"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
		, "LDS_TEMP_SRC_INUR"."PS_PARTKEY" AS "PS_PARTKEY"
		, "LDS_TEMP_SRC_INUR"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, "LDS_TEMP_SRC_INUR"."LOAD_DATE" AS "LOAD_DATE"
		, "LDS_TEMP_SRC_INUR"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "LDS_TEMP_SRC_INUR"."HASH_DIFF" AS "HASH_DIFF"
		, "LDS_TEMP_SRC_INUR"."DELETE_FLAG" AS "DELETE_FLAG"
		, "LDS_TEMP_SRC_INUR"."P_NAME" AS "P_NAME"
		, "LDS_TEMP_SRC_INUR"."P_SIZE" AS "P_SIZE"
		, "LDS_TEMP_SRC_INUR"."S_NAME" AS "S_NAME"
		, "LDS_TEMP_SRC_INUR"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "LDS_TEMP_SRC_INUR"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "LDS_TEMP_SRC_INUR"."PS_COMMENT" AS "PS_COMMENT"
		, "LDS_TEMP_SRC_INUR"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM {{ ref('VS_DEMO_TC_STG_S_SF1_SF1_PARTSUPP_LDS_TMP') }} "LDS_TEMP_SRC_INUR"
	WHERE  "LDS_TEMP_SRC_INUR"."SOURCE" = 'STG' AND "LDS_TEMP_SRC_INUR"."EQUAL" = 0

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "STG_DL_SRC" AS 
	( 
		SELECT 
			  "STG_DL_INR_SRC"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
			, "STG_DL_INR_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
			, "STG_DL_INR_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "STG_DL_INR_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_DL_INR_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_DL_INR_SRC"."P_NAME"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_DL_INR_SRC"."P_SIZE")
				),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_DL_INR_SRC"."S_NAME"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_DL_INR_SRC"."PS_AVAILQTY")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_DL_INR_SRC"."PS_SUPPLYCOST")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_DL_INR_SRC"."PS_COMMENT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_DL_INR_SRC"."DSS_RECORD_SOURCE"),'~'),'^','\\' || '^')|| '^','^' || '~'),'~') )) AS "HASH_DIFF"
			, CAST('N' AS VARCHAR) AS "DELETE_FLAG"
			, "STG_DL_INR_SRC"."P_NAME" AS "P_NAME"
			, "STG_DL_INR_SRC"."P_SIZE" AS "P_SIZE"
			, "STG_DL_INR_SRC"."S_NAME" AS "S_NAME"
			, "STG_DL_INR_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "STG_DL_INR_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "STG_DL_INR_SRC"."PS_COMMENT" AS "PS_COMMENT"
			, "STG_DL_INR_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
			, ROW_NUMBER()OVER(PARTITION BY "STG_DL_INR_SRC"."LND_SF1_PARTSUPP_HKEY" ORDER BY "STG_DL_INR_SRC"."LOAD_DATE") AS "DUMMY"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP') }} "STG_DL_INR_SRC"
	)
	SELECT 
		  "STG_DL_SRC"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
		, "STG_DL_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
		, "STG_DL_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, "STG_DL_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "STG_DL_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "STG_DL_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "STG_DL_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
		, "STG_DL_SRC"."P_NAME" AS "P_NAME"
		, "STG_DL_SRC"."P_SIZE" AS "P_SIZE"
		, "STG_DL_SRC"."S_NAME" AS "S_NAME"
		, "STG_DL_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "STG_DL_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "STG_DL_SRC"."PS_COMMENT" AS "PS_COMMENT"
		, "STG_DL_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "STG_DL_SRC" "STG_DL_SRC"
	WHERE  "STG_DL_SRC"."DUMMY" = 1

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'