{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='S_SF1_SF1_PARTSUPP_LDS_TMP',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'LDS_SF1_SF1PARTSUPP_INCR']
	)
}}
select * from (
	WITH "DIST_STG" AS 
	( 
		SELECT 
			  "STG_DIS_SRC"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MIN("STG_DIS_SRC"."LOAD_DATE") AS "MIN_LOAD_TIMESTAMP"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP') }} "STG_DIS_SRC"
		GROUP BY  "STG_DIS_SRC"."LND_SF1_PARTSUPP_HKEY",  "STG_DIS_SRC"."LOAD_CYCLE_ID"
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
			, "STG_TEMP_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_TEMP_SRC"."PART_HKEY" AS "PART_HKEY"
			, "STG_TEMP_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
			, "STG_TEMP_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP(NULL, 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_NAME"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."P_SIZE")
				),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."S_NAME"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."PS_AVAILQTY")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."PS_SUPPLYCOST")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."PS_COMMENT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."DSS_RECORD_SOURCE"),'~'),'^','\\' || '^')|| '^','^' || '~'),'~') )) AS "HASH_DIFF"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."P_NAME" AS "P_NAME"
			, "STG_TEMP_SRC"."P_SIZE" AS "P_SIZE"
			, "STG_TEMP_SRC"."S_NAME" AS "S_NAME"
			, "STG_TEMP_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "STG_TEMP_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "STG_TEMP_SRC"."PS_COMMENT" AS "PS_COMMENT"
			, "STG_TEMP_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PARTSUPP') }} "STG_TEMP_SRC"
		UNION ALL 
		SELECT 
			  "LDS_SRC"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
			, "LND_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "LND_SRC"."PART_HKEY" AS "PART_HKEY"
			, "LDS_SRC"."PS_PARTKEY" AS "PS_PARTKEY"
			, "LDS_SRC"."PS_SUPPKEY" AS "PS_SUPPKEY"
			, "LDS_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LDS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MAX("LDS_SRC"."LOAD_DATE")OVER(PARTITION BY "LDS_SRC"."LND_SF1_PARTSUPP_HKEY") AS "LOAD_END_DATE"
			, "LDS_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, 'SAT' AS "RECORD_TYPE"
			, 'LDS' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "LDS_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "LDS_SRC"."P_NAME" AS "P_NAME"
			, "LDS_SRC"."P_SIZE" AS "P_SIZE"
			, "LDS_SRC"."S_NAME" AS "S_NAME"
			, "LDS_SRC"."PS_AVAILQTY" AS "PS_AVAILQTY"
			, "LDS_SRC"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
			, "LDS_SRC"."PS_COMMENT" AS "PS_COMMENT"
			, "LDS_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('RDV', 'S_SF1_SF1_PARTSUPP_LDS') }} "LDS_SRC"
		INNER JOIN {{ source('RDV', 'L_SF1_PARTSUPP_LND') }} "LND_SRC" ON  "LDS_SRC"."LND_SF1_PARTSUPP_HKEY" = "LND_SRC"."LND_SF1_PARTSUPP_HKEY"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "LDS_SRC"."LND_SF1_PARTSUPP_HKEY" = "DIST_STG"."LND_SF1_PARTSUPP_HKEY"
	)
	SELECT 
		  "TEMP_TABLE_SET"."LND_SF1_PARTSUPP_HKEY" AS "LND_SF1_PARTSUPP_HKEY"
		, "TEMP_TABLE_SET"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "TEMP_TABLE_SET"."PART_HKEY" AS "PART_HKEY"
		, "TEMP_TABLE_SET"."PS_PARTKEY" AS "PS_PARTKEY"
		, "TEMP_TABLE_SET"."PS_SUPPKEY" AS "PS_SUPPKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."LND_SF1_PARTSUPP_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."P_NAME" AS "P_NAME"
		, "TEMP_TABLE_SET"."P_SIZE" AS "P_SIZE"
		, "TEMP_TABLE_SET"."S_NAME" AS "S_NAME"
		, "TEMP_TABLE_SET"."PS_AVAILQTY" AS "PS_AVAILQTY"
		, "TEMP_TABLE_SET"."PS_SUPPLYCOST" AS "PS_SUPPLYCOST"
		, "TEMP_TABLE_SET"."PS_COMMENT" AS "PS_COMMENT"
		, "TEMP_TABLE_SET"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"
	WHERE  "TEMP_TABLE_SET"."SOURCE" = 'STG' OR("TEMP_TABLE_SET"."LOAD_DATE" = "TEMP_TABLE_SET"."LOAD_END_DATE" AND "TEMP_TABLE_SET"."SOURCE" = 'LDS')

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'