{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='S_SF1_SF1_LINEITEM_LDS_TMP',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'LDS_SF1_SF1LINEITEM_INCR']
	)
}}
select * from (
	WITH "DIST_STG" AS 
	( 
		SELECT 
			  "STG_DIS_SRC"."LND_SF1_LINEITEM_HKEY" AS "LND_SF1_LINEITEM_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MIN("STG_DIS_SRC"."LOAD_DATE") AS "MIN_LOAD_TIMESTAMP"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_LINEITEM') }} "STG_DIS_SRC"
		GROUP BY  "STG_DIS_SRC"."LND_SF1_LINEITEM_HKEY",  "STG_DIS_SRC"."LOAD_CYCLE_ID"
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."LND_SF1_LINEITEM_HKEY" AS "LND_SF1_LINEITEM_HKEY"
			, "STG_TEMP_SRC"."PART_HKEY" AS "PART_HKEY"
			, "STG_TEMP_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_TEMP_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
			, "STG_TEMP_SRC"."L_ORDERKEY" AS "L_ORDERKEY"
			, "STG_TEMP_SRC"."L_LINENUMBER" AS "L_LINENUMBER"
			, "STG_TEMP_SRC"."L_PARTKEY" AS "L_PARTKEY"
			, "STG_TEMP_SRC"."L_SUPPKEY" AS "L_SUPPKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP(NULL, 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_NAME"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."P_SIZE")
				),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."S_NAME"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_LINENUMBER")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_QUANTITY")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_EXTENDEDPRICE")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_DISCOUNT")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_TAX")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."L_RETURNFLAG"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."L_LINESTATUS"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_SHIPDATE", 'DD/MM/YYYY')),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_COMMITDATE", 'DD/MM/YYYY')),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."L_RECEIPTDATE", 'DD/MM/YYYY')),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."L_SHIPINSTRUCT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."L_SHIPMODE"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."L_COMMENT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."DSS_RECORD_SOURCE"),'~'),'^','\\' || '^')|| '^','^' || '~'),'~') )) AS "HASH_DIFF"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."P_NAME" AS "P_NAME"
			, "STG_TEMP_SRC"."P_SIZE" AS "P_SIZE"
			, "STG_TEMP_SRC"."S_NAME" AS "S_NAME"
			, "STG_TEMP_SRC"."L_QUANTITY" AS "L_QUANTITY"
			, "STG_TEMP_SRC"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "STG_TEMP_SRC"."L_DISCOUNT" AS "L_DISCOUNT"
			, "STG_TEMP_SRC"."L_TAX" AS "L_TAX"
			, "STG_TEMP_SRC"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "STG_TEMP_SRC"."L_LINESTATUS" AS "L_LINESTATUS"
			, "STG_TEMP_SRC"."L_SHIPDATE" AS "L_SHIPDATE"
			, "STG_TEMP_SRC"."L_COMMITDATE" AS "L_COMMITDATE"
			, "STG_TEMP_SRC"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "STG_TEMP_SRC"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "STG_TEMP_SRC"."L_SHIPMODE" AS "L_SHIPMODE"
			, "STG_TEMP_SRC"."L_COMMENT" AS "L_COMMENT"
			, "STG_TEMP_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_LINEITEM') }} "STG_TEMP_SRC"
		UNION ALL 
		SELECT 
			  "LDS_SRC"."LND_SF1_LINEITEM_HKEY" AS "LND_SF1_LINEITEM_HKEY"
			, "LND_SRC"."PART_HKEY" AS "PART_HKEY"
			, "LND_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "LND_SRC"."ORDER_HKEY" AS "ORDER_HKEY"
			, "LDS_SRC"."L_ORDERKEY" AS "L_ORDERKEY"
			, "LDS_SRC"."L_LINENUMBER" AS "L_LINENUMBER"
			, "LDS_SRC"."L_PARTKEY" AS "L_PARTKEY"
			, "LDS_SRC"."L_SUPPKEY" AS "L_SUPPKEY"
			, "LDS_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "LDS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MAX("LDS_SRC"."LOAD_DATE")OVER(PARTITION BY "LDS_SRC"."LND_SF1_LINEITEM_HKEY") AS "LOAD_END_DATE"
			, "LDS_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, 'SAT' AS "RECORD_TYPE"
			, 'LDS' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "LDS_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "LDS_SRC"."P_NAME" AS "P_NAME"
			, "LDS_SRC"."P_SIZE" AS "P_SIZE"
			, "LDS_SRC"."S_NAME" AS "S_NAME"
			, "LDS_SRC"."L_QUANTITY" AS "L_QUANTITY"
			, "LDS_SRC"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "LDS_SRC"."L_DISCOUNT" AS "L_DISCOUNT"
			, "LDS_SRC"."L_TAX" AS "L_TAX"
			, "LDS_SRC"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "LDS_SRC"."L_LINESTATUS" AS "L_LINESTATUS"
			, "LDS_SRC"."L_SHIPDATE" AS "L_SHIPDATE"
			, "LDS_SRC"."L_COMMITDATE" AS "L_COMMITDATE"
			, "LDS_SRC"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "LDS_SRC"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "LDS_SRC"."L_SHIPMODE" AS "L_SHIPMODE"
			, "LDS_SRC"."L_COMMENT" AS "L_COMMENT"
			, "LDS_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('RDV', 'S_SF1_SF1_LINEITEM_LDS') }} "LDS_SRC"
		INNER JOIN {{ source('RDV', 'L_SF1_LINEITEM_LND') }} "LND_SRC" ON  "LDS_SRC"."LND_SF1_LINEITEM_HKEY" = "LND_SRC"."LND_SF1_LINEITEM_HKEY"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "LDS_SRC"."LND_SF1_LINEITEM_HKEY" = "DIST_STG"."LND_SF1_LINEITEM_HKEY"
	)
	SELECT 
		  "TEMP_TABLE_SET"."LND_SF1_LINEITEM_HKEY" AS "LND_SF1_LINEITEM_HKEY"
		, "TEMP_TABLE_SET"."PART_HKEY" AS "PART_HKEY"
		, "TEMP_TABLE_SET"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "TEMP_TABLE_SET"."ORDER_HKEY" AS "ORDER_HKEY"
		, "TEMP_TABLE_SET"."L_ORDERKEY" AS "L_ORDERKEY"
		, "TEMP_TABLE_SET"."L_LINENUMBER" AS "L_LINENUMBER"
		, "TEMP_TABLE_SET"."L_PARTKEY" AS "L_PARTKEY"
		, "TEMP_TABLE_SET"."L_SUPPKEY" AS "L_SUPPKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."LND_SF1_LINEITEM_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."P_NAME" AS "P_NAME"
		, "TEMP_TABLE_SET"."P_SIZE" AS "P_SIZE"
		, "TEMP_TABLE_SET"."S_NAME" AS "S_NAME"
		, "TEMP_TABLE_SET"."L_QUANTITY" AS "L_QUANTITY"
		, "TEMP_TABLE_SET"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
		, "TEMP_TABLE_SET"."L_DISCOUNT" AS "L_DISCOUNT"
		, "TEMP_TABLE_SET"."L_TAX" AS "L_TAX"
		, "TEMP_TABLE_SET"."L_RETURNFLAG" AS "L_RETURNFLAG"
		, "TEMP_TABLE_SET"."L_LINESTATUS" AS "L_LINESTATUS"
		, "TEMP_TABLE_SET"."L_SHIPDATE" AS "L_SHIPDATE"
		, "TEMP_TABLE_SET"."L_COMMITDATE" AS "L_COMMITDATE"
		, "TEMP_TABLE_SET"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
		, "TEMP_TABLE_SET"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
		, "TEMP_TABLE_SET"."L_SHIPMODE" AS "L_SHIPMODE"
		, "TEMP_TABLE_SET"."L_COMMENT" AS "L_COMMENT"
		, "TEMP_TABLE_SET"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"
	WHERE  "TEMP_TABLE_SET"."SOURCE" = 'STG' OR("TEMP_TABLE_SET"."LOAD_DATE" = "TEMP_TABLE_SET"."LOAD_END_DATE" AND "TEMP_TABLE_SET"."SOURCE" = 'LDS')

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'