{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='S_SF1_CUSTOMER_TMP',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'SAT_SF1_CUSTOMER_INCR']
	)
}}
select * from (
	WITH "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP(NULL, 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."C_ADDRESS"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."C_NATIONKEY")
				),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."C_PHONE"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."C_ACCTBAL")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."C_MKTSEGMENT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."C_COMMENT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."DSS_RECORD_SOURCE"),'~'),'^','\\' || '^')|| '^','^' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."C_CUSTKEY" AS "C_CUSTKEY"
			, "STG_TEMP_SRC"."C_NAME" AS "C_NAME"
			, "STG_TEMP_SRC"."C_ADDRESS" AS "C_ADDRESS"
			, "STG_TEMP_SRC"."C_NATIONKEY" AS "C_NATIONKEY"
			, "STG_TEMP_SRC"."C_PHONE" AS "C_PHONE"
			, "STG_TEMP_SRC"."C_ACCTBAL" AS "C_ACCTBAL"
			, "STG_TEMP_SRC"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "STG_TEMP_SRC"."C_COMMENT" AS "C_COMMENT"
			, "STG_TEMP_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER') }} "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MAX("SAT_SRC"."LOAD_DATE")OVER( PARTITION BY "SAT_SRC"."CUSTOMER_HKEY") AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."C_CUSTKEY" AS "C_CUSTKEY"
			, "SAT_SRC"."C_NAME" AS "C_NAME"
			, "SAT_SRC"."C_ADDRESS" AS "C_ADDRESS"
			, "SAT_SRC"."C_NATIONKEY" AS "C_NATIONKEY"
			, "SAT_SRC"."C_PHONE" AS "C_PHONE"
			, "SAT_SRC"."C_ACCTBAL" AS "C_ACCTBAL"
			, "SAT_SRC"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "SAT_SRC"."C_COMMENT" AS "C_COMMENT"
			, "SAT_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('RDV', 'S_SF1_CUSTOMER') }} "SAT_SRC"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_SF1_CUSTOMER') }} "STG_TEMP_SAT_SRC" ON  "SAT_SRC"."CUSTOMER_HKEY" = "STG_TEMP_SAT_SRC"."CUSTOMER_HKEY"
		WHERE  "STG_TEMP_SAT_SRC"."RECORD_TYPE" = 'S'
	)
	SELECT 
		  "TEMP_TABLE_SET"."CUSTOMER_HKEY" AS "CUSTOMER_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."CUSTOMER_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."C_CUSTKEY" AS "C_CUSTKEY"
		, "TEMP_TABLE_SET"."C_NAME" AS "C_NAME"
		, "TEMP_TABLE_SET"."C_ADDRESS" AS "C_ADDRESS"
		, "TEMP_TABLE_SET"."C_NATIONKEY" AS "C_NATIONKEY"
		, "TEMP_TABLE_SET"."C_PHONE" AS "C_PHONE"
		, "TEMP_TABLE_SET"."C_ACCTBAL" AS "C_ACCTBAL"
		, "TEMP_TABLE_SET"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
		, "TEMP_TABLE_SET"."C_COMMENT" AS "C_COMMENT"
		, "TEMP_TABLE_SET"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"
	WHERE  "TEMP_TABLE_SET"."SOURCE" = 'STG' OR("TEMP_TABLE_SET"."LOAD_DATE" = "TEMP_TABLE_SET"."LOAD_END_DATE" AND "TEMP_TABLE_SET"."SOURCE" = 'SAT')

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'