{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='S_SF1_PART_TMP',
		schema='VS_DEMO_TC_STG',
		tags=['VS_DEMO_TC', 'SAT_SF1_PART_INCR']
	)
}}
select * from (
	WITH "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."PART_HKEY" AS "PART_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP(NULL, 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_MFGR"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_BRAND")
				,'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_TYPE"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_CONTAINER"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."P_RETAILPRICE")),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_COMMENT"),'~'),'^','\\' || '^')|| '^' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."DSS_RECORD_SOURCE"),'~'),'^','\\' || '^')|| '^','^' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."P_PARTKEY" AS "P_PARTKEY"
			, "STG_TEMP_SRC"."P_NAME" AS "P_NAME"
			, "STG_TEMP_SRC"."P_SIZE" AS "P_SIZE"
			, "STG_TEMP_SRC"."P_MFGR" AS "P_MFGR"
			, "STG_TEMP_SRC"."P_BRAND" AS "P_BRAND"
			, "STG_TEMP_SRC"."P_TYPE" AS "P_TYPE"
			, "STG_TEMP_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "STG_TEMP_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "STG_TEMP_SRC"."P_COMMENT" AS "P_COMMENT"
			, "STG_TEMP_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_STG_SF1_PART') }} "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."PART_HKEY" AS "PART_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MAX("SAT_SRC"."LOAD_DATE")OVER( PARTITION BY "SAT_SRC"."PART_HKEY") AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."P_PARTKEY" AS "P_PARTKEY"
			, "SAT_SRC"."P_NAME" AS "P_NAME"
			, "SAT_SRC"."P_SIZE" AS "P_SIZE"
			, "SAT_SRC"."P_MFGR" AS "P_MFGR"
			, "SAT_SRC"."P_BRAND" AS "P_BRAND"
			, "SAT_SRC"."P_TYPE" AS "P_TYPE"
			, "SAT_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "SAT_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "SAT_SRC"."P_COMMENT" AS "P_COMMENT"
			, "SAT_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('RDV', 'S_SF1_PART') }} "SAT_SRC"
		INNER JOIN {{ ref('VS_DEMO_TC_STG_SF1_PART') }} "STG_TEMP_SAT_SRC" ON  "SAT_SRC"."PART_HKEY" = "STG_TEMP_SAT_SRC"."PART_HKEY"
		WHERE  "STG_TEMP_SAT_SRC"."RECORD_TYPE" = 'S'
	)
	SELECT 
		  "TEMP_TABLE_SET"."PART_HKEY" AS "PART_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF")
			= LAG( TO_CHAR("TEMP_TABLE_SET"."DELETE_FLAG") || TO_CHAR("TEMP_TABLE_SET"."HASH_DIFF"),1)OVER(PARTITION BY "TEMP_TABLE_SET"."PART_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."P_PARTKEY" AS "P_PARTKEY"
		, "TEMP_TABLE_SET"."P_NAME" AS "P_NAME"
		, "TEMP_TABLE_SET"."P_SIZE" AS "P_SIZE"
		, "TEMP_TABLE_SET"."P_MFGR" AS "P_MFGR"
		, "TEMP_TABLE_SET"."P_BRAND" AS "P_BRAND"
		, "TEMP_TABLE_SET"."P_TYPE" AS "P_TYPE"
		, "TEMP_TABLE_SET"."P_CONTAINER" AS "P_CONTAINER"
		, "TEMP_TABLE_SET"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "TEMP_TABLE_SET"."P_COMMENT" AS "P_COMMENT"
		, "TEMP_TABLE_SET"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"
	WHERE  "TEMP_TABLE_SET"."SOURCE" = 'STG' OR("TEMP_TABLE_SET"."LOAD_DATE" = "TEMP_TABLE_SET"."LOAD_END_DATE" AND "TEMP_TABLE_SET"."SOURCE" = 'SAT')

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'