/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.10, generation date: 2023/06/16 19:12:05
DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00
 */

/* DROP TABLES */

-- START
DROP TABLE IF EXISTS "VS_DEMO_TC_STG"."S_SF1_ORDERCUST_LDS_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "VS_DEMO_TC_STG"."S_SF1_SF1_LINEITEM_LDS_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "VS_DEMO_TC_STG"."S_SF1_SF1_PARTSUPP_LDS_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "VS_DEMO_TC_STG"."S_SF1_CUSTOMER_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "VS_DEMO_TC_STG"."S_SF1_ORDER_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "VS_DEMO_TC_STG"."S_SF1_PART_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "VS_DEMO_TC_STG"."S_SF1_SUPPLIER_TMP" 
CASCADE
;

-- END


/* CREATE TABLES */

-- START

CREATE   TABLE "VS_DEMO_TC_STG"."S_SF1_CUSTOMER_TMP"
(
    "CUSTOMER_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"C_CUSTKEY" NUMBER
   ,"C_ADDRESS" VARCHAR(40)
   ,"C_NATIONKEY" NUMBER
   ,"C_PHONE" VARCHAR(15)
   ,"C_ACCTBAL" NUMBER
   ,"C_MKTSEGMENT" VARCHAR(10)
   ,"C_COMMENT" VARCHAR(117)
   ,"DSS_RECORD_SOURCE" VARCHAR(39)
   ,"C_NAME" VARCHAR(25)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "VS_DEMO_TC_STG"."S_SF1_CUSTOMER_TMP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00';


CREATE   TABLE "VS_DEMO_TC_STG"."S_SF1_ORDER_TMP"
(
    "ORDER_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"O_ORDERKEY" NUMBER
   ,"C_NAME" VARCHAR(25)
   ,"O_ORDERSTATUS" VARCHAR(3)
   ,"O_TOTALPRICE" NUMBER
   ,"O_ORDERDATE" DATE
   ,"O_ORDERPRIORITY" VARCHAR(15)
   ,"O_CLERK" VARCHAR(15)
   ,"O_SHIPPRIORITY" NUMBER
   ,"O_COMMENT" VARCHAR(79)
   ,"DSS_RECORD_SOURCE" VARCHAR(37)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "VS_DEMO_TC_STG"."S_SF1_ORDER_TMP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00';


CREATE   TABLE "VS_DEMO_TC_STG"."S_SF1_PART_TMP"
(
    "PART_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"P_PARTKEY" NUMBER
   ,"P_MFGR" VARCHAR(25)
   ,"P_BRAND" VARCHAR(10)
   ,"P_TYPE" VARCHAR(25)
   ,"P_CONTAINER" VARCHAR(10)
   ,"P_RETAILPRICE" NUMBER
   ,"P_COMMENT" VARCHAR(23)
   ,"DSS_RECORD_SOURCE" VARCHAR(35)
   ,"P_NAME" VARCHAR(55)
   ,"P_SIZE" NUMBER
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "VS_DEMO_TC_STG"."S_SF1_PART_TMP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00';


CREATE   TABLE "VS_DEMO_TC_STG"."S_SF1_SUPPLIER_TMP"
(
    "SUPPLIER_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"S_SUPPKEY" NUMBER
   ,"S_ADDRESS" VARCHAR(40)
   ,"S_NATIONKEY" NUMBER
   ,"S_PHONE" VARCHAR(15)
   ,"S_ACCTBAL" NUMBER
   ,"S_COMMENT" VARCHAR(101)
   ,"DSS_RECORD_SOURCE" VARCHAR(39)
   ,"S_NAME" VARCHAR(25)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "VS_DEMO_TC_STG"."S_SF1_SUPPLIER_TMP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00';


CREATE   TABLE "VS_DEMO_TC_STG"."S_SF1_ORDERCUST_LDS_TMP"
(
    "LND_ORDERCUST_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"O_CUSTKEY" NUMBER DEFAULT -1 NOT NULL
   ,"O_ORDERKEY" NUMBER DEFAULT -1 NOT NULL
   ,"C_NAME" VARCHAR(25)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
   ,"ORDER_HKEY" VARCHAR(32)
   ,"CUSTOMER_HKEY" VARCHAR(32)
)
;

COMMENT ON TABLE "VS_DEMO_TC_STG"."S_SF1_ORDERCUST_LDS_TMP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00';


CREATE   TABLE "VS_DEMO_TC_STG"."S_SF1_SF1_LINEITEM_LDS_TMP"
(
    "LND_SF1_LINEITEM_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"L_ORDERKEY" NUMBER DEFAULT -1 NOT NULL
   ,"L_PARTKEY" NUMBER
   ,"L_LINENUMBER" NUMBER DEFAULT -1 NOT NULL
   ,"L_SUPPKEY" NUMBER
   ,"P_NAME" VARCHAR(55)
   ,"P_SIZE" NUMBER
   ,"S_NAME" VARCHAR(25)
   ,"L_QUANTITY" NUMBER
   ,"L_EXTENDEDPRICE" NUMBER
   ,"L_DISCOUNT" NUMBER
   ,"L_TAX" NUMBER
   ,"L_RETURNFLAG" VARCHAR(3)
   ,"L_LINESTATUS" VARCHAR(3)
   ,"L_SHIPDATE" DATE
   ,"L_COMMITDATE" DATE
   ,"L_RECEIPTDATE" DATE
   ,"L_SHIPINSTRUCT" VARCHAR(25)
   ,"L_SHIPMODE" VARCHAR(10)
   ,"L_COMMENT" VARCHAR(44)
   ,"DSS_RECORD_SOURCE" VARCHAR(39)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
   ,"ORDER_HKEY" VARCHAR(32)
   ,"SUPPLIER_HKEY" VARCHAR(32)
   ,"PART_HKEY" VARCHAR(32)
)
;

COMMENT ON TABLE "VS_DEMO_TC_STG"."S_SF1_SF1_LINEITEM_LDS_TMP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00';


CREATE   TABLE "VS_DEMO_TC_STG"."S_SF1_SF1_PARTSUPP_LDS_TMP"
(
    "LND_SF1_PARTSUPP_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/1900 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"PS_PARTKEY" NUMBER DEFAULT -1 NOT NULL
   ,"PS_SUPPKEY" NUMBER DEFAULT -1 NOT NULL
   ,"P_NAME" VARCHAR(55)
   ,"P_SIZE" NUMBER
   ,"S_NAME" VARCHAR(25)
   ,"PS_AVAILQTY" NUMBER
   ,"PS_SUPPLYCOST" NUMBER
   ,"PS_COMMENT" VARCHAR(199)
   ,"DSS_RECORD_SOURCE" VARCHAR(39)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
   ,"PART_HKEY" VARCHAR(32)
   ,"SUPPLIER_HKEY" VARCHAR(32)
)
;

COMMENT ON TABLE "VS_DEMO_TC_STG"."S_SF1_SF1_PARTSUPP_LDS_TMP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00';


-- END


