/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.10, generation date: 2023/06/16 19:12:05
DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21
 */

/* DROP TABLES */

-- START
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_ORDER" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_SUPPLIER" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_PART" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_CUSTOMER" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_SF1_LINEITEM" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_ORDERCUST" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_SF1_PARTSUPP" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_TRANS_ORDER" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_TRANS_SUPPLIER" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_TRANS_PART" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_TRANS_CUSTOMER" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_TRANS_SF1_LINEITEM" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_TRANS_ORDERCUST" 
CASCADE
;
DROP TABLE IF EXISTS "BV"."PIT_DETAIL_TRANS_SF1_PARTSUPP" 
CASCADE
;
DROP TABLE IF EXISTS "DV_MTD"."FMC_BV_LOADING_WINDOW_TABLE" 
CASCADE
;
DROP TABLE IF EXISTS "DV_MTD"."LOAD_CYCLE_INFO" 
CASCADE
;
DROP TABLE IF EXISTS "DV_MTD"."DV_LOAD_CYCLE_INFO" 
CASCADE
;

-- END


/* CREATE TABLES */

-- START

CREATE   TABLE "BV"."PIT_DETAIL_ORDER"
(
	 "PIT_DETAIL_ORDER_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"ORDER_HKEY" VARCHAR(32)
	,"S_SF1_ORDER_HKEY" VARCHAR(32)
	,"S_SF1_ORDER_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_ORDER_PK" PRIMARY KEY ("PIT_DETAIL_ORDER_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_ORDER_UK" UNIQUE ("ORDER_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_ORDER" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_SUPPLIER"
(
	 "PIT_DETAIL_SUPPLIER_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"SUPPLIER_HKEY" VARCHAR(32)
	,"S_SF1_SUPPLIER_HKEY" VARCHAR(32)
	,"S_SF1_SUPPLIER_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_SUPPLIER_PK" PRIMARY KEY ("PIT_DETAIL_SUPPLIER_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_SUPPLIER_UK" UNIQUE ("SUPPLIER_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_SUPPLIER" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_PART"
(
	 "PIT_DETAIL_PART_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"PART_HKEY" VARCHAR(32)
	,"S_SF1_PART_HKEY" VARCHAR(32)
	,"S_SF1_PART_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_PART_PK" PRIMARY KEY ("PIT_DETAIL_PART_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_PART_UK" UNIQUE ("PART_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_PART" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_CUSTOMER"
(
	 "PIT_DETAIL_CUSTOMER_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"CUSTOMER_HKEY" VARCHAR(32)
	,"S_SF1_CUSTOMER_HKEY" VARCHAR(32)
	,"S_SF1_CUSTOMER_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_CUSTOMER_PK" PRIMARY KEY ("PIT_DETAIL_CUSTOMER_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_CUSTOMER_UK" UNIQUE ("CUSTOMER_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_CUSTOMER" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_SF1_LINEITEM"
(
	 "PIT_DETAIL_SF1_LINEITEM_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"LND_SF1_LINEITEM_HKEY" VARCHAR(32)
	,"S_SF1_SF1_LINEITEM_LDS_HKEY" VARCHAR(32)
	,"S_SF1_SF1_LINEITEM_LDS_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_SF1_LINEITEM_PK" PRIMARY KEY ("PIT_DETAIL_SF1_LINEITEM_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_SF1_LINEITEM_UK" UNIQUE ("LND_SF1_LINEITEM_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_SF1_LINEITEM" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_ORDERCUST"
(
	 "PIT_DETAIL_ORDERCUST_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"LND_ORDERCUST_HKEY" VARCHAR(32)
	,"S_SF1_ORDERCUST_LDS_HKEY" VARCHAR(32)
	,"S_SF1_ORDERCUST_LDS_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_ORDERCUST_PK" PRIMARY KEY ("PIT_DETAIL_ORDERCUST_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_ORDERCUST_UK" UNIQUE ("LND_ORDERCUST_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_ORDERCUST" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_SF1_PARTSUPP"
(
	 "PIT_DETAIL_SF1_PARTSUPP_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"LND_SF1_PARTSUPP_HKEY" VARCHAR(32)
	,"S_SF1_SF1_PARTSUPP_LDS_HKEY" VARCHAR(32)
	,"S_SF1_SF1_PARTSUPP_LDS_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_SF1_PARTSUPP_PK" PRIMARY KEY ("PIT_DETAIL_SF1_PARTSUPP_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_SF1_PARTSUPP_UK" UNIQUE ("LND_SF1_PARTSUPP_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_SF1_PARTSUPP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_TRANS_ORDER"
(
	 "PIT_DETAIL_TRANS_ORDER_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"ORDER_HKEY" VARCHAR(32)
	,"S_SF1_ORDER_HKEY" VARCHAR(32)
	,"S_SF1_ORDER_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_TRANS_ORDER_PK" PRIMARY KEY ("PIT_DETAIL_TRANS_ORDER_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_TRANS_ORDER_UK" UNIQUE ("ORDER_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_TRANS_ORDER" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_TRANS_SUPPLIER"
(
	 "PIT_DETAIL_TRANS_SUPPLIER_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"SUPPLIER_HKEY" VARCHAR(32)
	,"S_SF1_SUPPLIER_HKEY" VARCHAR(32)
	,"S_SF1_SUPPLIER_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_TRANS_SUPPLIER_PK" PRIMARY KEY ("PIT_DETAIL_TRANS_SUPPLIER_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_TRANS_SUPPLIER_UK" UNIQUE ("SUPPLIER_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_TRANS_SUPPLIER" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_TRANS_PART"
(
	 "PIT_DETAIL_TRANS_PART_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"PART_HKEY" VARCHAR(32)
	,"S_SF1_PART_HKEY" VARCHAR(32)
	,"S_SF1_PART_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_TRANS_PART_PK" PRIMARY KEY ("PIT_DETAIL_TRANS_PART_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_TRANS_PART_UK" UNIQUE ("PART_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_TRANS_PART" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_TRANS_CUSTOMER"
(
	 "PIT_DETAIL_TRANS_CUSTOMER_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"CUSTOMER_HKEY" VARCHAR(32)
	,"S_SF1_CUSTOMER_HKEY" VARCHAR(32)
	,"S_SF1_CUSTOMER_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_TRANS_CUSTOMER_PK" PRIMARY KEY ("PIT_DETAIL_TRANS_CUSTOMER_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_TRANS_CUSTOMER_UK" UNIQUE ("CUSTOMER_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_TRANS_CUSTOMER" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_TRANS_SF1_LINEITEM"
(
	 "PIT_DETAIL_TRANS_SF1_LINEITEM_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"LND_SF1_LINEITEM_HKEY" VARCHAR(32)
	,"S_SF1_SF1_LINEITEM_LDS_HKEY" VARCHAR(32)
	,"S_SF1_SF1_LINEITEM_LDS_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_TRANS_SF1_LINEITEM_PK" PRIMARY KEY ("PIT_DETAIL_TRANS_SF1_LINEITEM_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_TRANS_SF1_LINEITEM_UK" UNIQUE ("LND_SF1_LINEITEM_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_TRANS_SF1_LINEITEM" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_TRANS_ORDERCUST"
(
	 "PIT_DETAIL_TRANS_ORDERCUST_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"LND_ORDERCUST_HKEY" VARCHAR(32)
	,"S_SF1_ORDERCUST_LDS_HKEY" VARCHAR(32)
	,"S_SF1_ORDERCUST_LDS_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_TRANS_ORDERCUST_PK" PRIMARY KEY ("PIT_DETAIL_TRANS_ORDERCUST_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_TRANS_ORDERCUST_UK" UNIQUE ("LND_ORDERCUST_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_TRANS_ORDERCUST" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "BV"."PIT_DETAIL_TRANS_SF1_PARTSUPP"
(
	 "PIT_DETAIL_TRANS_SF1_PARTSUPP_HKEY" VARCHAR(32)
	,"SNAPSHOT_TIMESTAMP" TIMESTAMP_NTZ
	,"LOAD_CYCLE_ID" INTEGER
	,"LND_SF1_PARTSUPP_HKEY" VARCHAR(32)
	,"S_SF1_SF1_PARTSUPP_LDS_HKEY" VARCHAR(32)
	,"S_SF1_SF1_PARTSUPP_LDS_LOAD_DATE" TIMESTAMP_NTZ
   ,CONSTRAINT "PIT_DETAIL_TRANS_SF1_PARTSUPP_PK" PRIMARY KEY ("PIT_DETAIL_TRANS_SF1_PARTSUPP_HKEY")   
   ,CONSTRAINT "PIT_DETAIL_TRANS_SF1_PARTSUPP_UK" UNIQUE ("LND_SF1_PARTSUPP_HKEY", "SNAPSHOT_TIMESTAMP")   
)
;

COMMENT ON TABLE "BV"."PIT_DETAIL_TRANS_SF1_PARTSUPP" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "DV_MTD"."FMC_BV_LOADING_WINDOW_TABLE"
(
	"FMC_BEGIN_LW_TIMESTAMP" TIMESTAMP_NTZ,
	"FMC_END_LW_TIMESTAMP" TIMESTAMP_NTZ
)
;

COMMENT ON TABLE "DV_MTD"."FMC_BV_LOADING_WINDOW_TABLE" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "DV_MTD"."LOAD_CYCLE_INFO"
(
	"LOAD_CYCLE_ID" INTEGER,
	"LOAD_DATE" TIMESTAMP_NTZ
)
;

COMMENT ON TABLE "DV_MTD"."LOAD_CYCLE_INFO" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


CREATE   TABLE "DV_MTD"."DV_LOAD_CYCLE_INFO"
(
	"DV_LOAD_CYCLE_ID" INTEGER
)
;

COMMENT ON TABLE "DV_MTD"."DV_LOAD_CYCLE_INFO" IS 'DV_NAME: DEMO_VS_TC - Release: concat all(13) - Comment: concat all - Release date: 2023/06/14 13:52:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/14 13:52:21';


-- END


