{{
	config(
		materialized='view',
		alias='DIM_CUSTOMER',
		schema='BV',
		tags=['view', 'BV', 'BV_ETL_DIM_CUSTOMER_SCD2_DIM_HUB']
	)
}}
	WITH "DVO_BASE" AS 
	( 
		SELECT 
			  "HUB_SRC"."CUSTOMER_HKEY" AS "BASE_OBJECT_H_KEY"
			, "HUB_SRC"."CUSTOMER_BK" AS "CUSTOMER_BK"
			, "PIT_SRC2"."SNAPSHOT_TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "SAT_SRC2_1"."C_ADDRESS" AS "C_ADDRESS"
			, "SAT_SRC2_1"."C_NATIONKEY" AS "C_NATIONKEY"
			, "SAT_SRC2_1"."C_PHONE" AS "C_PHONE"
			, "SAT_SRC2_1"."C_ACCTBAL" AS "C_ACCTBAL"
			, "SAT_SRC2_1"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "SAT_SRC2_1"."C_COMMENT" AS "C_COMMENT"
			, UPPER(MD5_HEX(  UPPER(REPLACE(COALESCE(TRIM( "HUB_SRC"."CUSTOMER_HKEY"),'~'),'^','\\' || '^'))
				||  || UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC2_1"."C_ADDRESS"),'~'),'^','\\' || '^'))|| '^' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC2_1"."C_NATIONKEY")),'~'),'^','\\' || '^'))|| '^' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC2_1"."C_PHONE"),'~'),'^','\\' || '^'))|| '^' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC2_1"."C_ACCTBAL")),'~'),'^','\\' || '^'))|| '^' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC2_1"."C_MKTSEGMENT"),'~'),'^','\\' || '^'))|| '^' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC2_1"."C_COMMENT"),'~'),'^','\\' || '^'))|| '^'  )) AS "DIM_HASH_DIFF"
		FROM {{ ref('RDV_H_CUSTOMER') }} "HUB_SRC"
		INNER JOIN {{ source('BV', 'PIT_DETAIL_TRANS_CUSTOMER') }} "PIT_SRC2" ON  "HUB_SRC"."CUSTOMER_HKEY" = "PIT_SRC2"."CUSTOMER_HKEY"
		INNER JOIN {{ ref('RDV_S_SF1_CUSTOMER') }} "SAT_SRC2_1" ON  "PIT_SRC2"."S_SF1_CUSTOMER_HKEY" = "SAT_SRC2_1"."CUSTOMER_HKEY"
	)
	, "HASH_DIFF_DATA_SET" AS 
	( 
		SELECT 
			  "DVO_BASE"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "DVO_BASE"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "DVO_BASE"."C_ADDRESS" AS "C_ADDRESS"
			, "DVO_BASE"."C_NATIONKEY" AS "C_NATIONKEY"
			, "DVO_BASE"."C_PHONE" AS "C_PHONE"
			, "DVO_BASE"."C_ACCTBAL" AS "C_ACCTBAL"
			, "DVO_BASE"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "DVO_BASE"."C_COMMENT" AS "C_COMMENT"
			, CASE WHEN COALESCE(LEAD("DVO_BASE"."DIM_HASH_DIFF")OVER(PARTITION BY "DVO_BASE"."BASE_OBJECT_H_KEY" ORDER BY "DVO_BASE"."SNAPSHOT__TIMESTAMP")
				,'XXX')!= "DVO_BASE"."DIM_HASH_DIFF" THEN 1 ELSE 0 END AS "CHANGE_FLAG"
		FROM "DVO_BASE" "DVO_BASE"
	)
	, "FILTERED_DATA_SET" AS 
	( 
		SELECT 
			  "HASH_DIFF_DATA_SET"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "HASH_DIFF_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "HASH_DIFF_DATA_SET"."C_ADDRESS" AS "C_ADDRESS"
			, "HASH_DIFF_DATA_SET"."C_NATIONKEY" AS "C_NATIONKEY"
			, "HASH_DIFF_DATA_SET"."C_PHONE" AS "C_PHONE"
			, "HASH_DIFF_DATA_SET"."C_ACCTBAL" AS "C_ACCTBAL"
			, "HASH_DIFF_DATA_SET"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
			, "HASH_DIFF_DATA_SET"."C_COMMENT" AS "C_COMMENT"
		FROM "HASH_DIFF_DATA_SET" "HASH_DIFF_DATA_SET"
		WHERE  "HASH_DIFF_DATA_SET"."CHANGE_FLAG" = 1
	)
	SELECT 
		  UPPER(MD5_HEX(  || UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP", 
			'DD/MM/YYYY HH24:MI:SS')),'~'),'^','\\' || '^'))|| '^'  )) AS "DIM_CUSTOMER_HKEY"
		, "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" AS "CUSTOMER_HKEY"
		, "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
		, COALESCE(LEAD("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")OVER(PARTITION BY "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" ORDER BY "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")
			, TO_TIMESTAMP('31/12/9999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')) AS "END_SNAPSHOT__TIMESTAMP"
		, "FILTERED_DATA_SET"."C_ADDRESS" AS "C_ADDRESS"
		, "FILTERED_DATA_SET"."C_NATIONKEY" AS "C_NATIONKEY"
		, "FILTERED_DATA_SET"."C_PHONE" AS "C_PHONE"
		, "FILTERED_DATA_SET"."C_ACCTBAL" AS "C_ACCTBAL"
		, "FILTERED_DATA_SET"."C_MKTSEGMENT" AS "C_MKTSEGMENT"
		, "FILTERED_DATA_SET"."C_COMMENT" AS "C_COMMENT"
	FROM "FILTERED_DATA_SET" "FILTERED_DATA_SET"
