{{
	config(
		materialized='view',
		alias='DIM_PART',
		schema='BV',
		tags=['view', 'BV', 'BV_ETL_DIM_PART_SCD2_DIM_HUB']
	)
}}
	WITH "DVO_BASE" AS 
	( 
		SELECT 
			  "HUB_SRC"."PART_HKEY" AS "BASE_OBJECT_H_KEY"
			, "HUB_SRC"."PART_BK" AS "PART_BK"
			, UPPER(MD5_HEX(  UPPER(REPLACE(COALESCE(TRIM( "HUB_SRC"."PART_HKEY"),'~'),'^','\\' || '^'))||     )) AS "DIM_HASH_DIFF"
		FROM {{ ref('RDV_H_PART') }} "HUB_SRC"
	)
	, "HASH_DIFF_DATA_SET" AS 
	( 
		SELECT 
			  "DVO_BASE"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "DVO_BASE"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, CASE WHEN COALESCE(LEAD("DVO_BASE"."DIM_HASH_DIFF")OVER(PARTITION BY "DVO_BASE"."BASE_OBJECT_H_KEY" ORDER BY "DVO_BASE"."SNAPSHOT__TIMESTAMP")
				,'XXX')!= "DVO_BASE"."DIM_HASH_DIFF" THEN 1 ELSE 0 END AS "CHANGE_FLAG"
		FROM "DVO_BASE" "DVO_BASE"
	)
	, "FILTERED_DATA_SET" AS 
	( 
		SELECT 
			  "HASH_DIFF_DATA_SET"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "HASH_DIFF_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
		FROM "HASH_DIFF_DATA_SET" "HASH_DIFF_DATA_SET"
		WHERE  "HASH_DIFF_DATA_SET"."CHANGE_FLAG" = 1
	)
	SELECT 
		  UPPER(MD5_HEX(  || UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP", 
			'DD/MM/YYYY HH24:MI:SS')),'~'),'^','\\' || '^'))|| '^'  )) AS "DIM_PART_HKEY"
		, "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" AS "PART_HKEY"
		, "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
		, COALESCE(LEAD("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")OVER(PARTITION BY "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" ORDER BY "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")
			, TO_TIMESTAMP('31/12/9999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')) AS "END_SNAPSHOT__TIMESTAMP"
	FROM "FILTERED_DATA_SET" "FILTERED_DATA_SET"
