{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_PART',
		schema='VS_DEMO_TC_EXT',
		tags=['VS_DEMO_TC', 'EXT_SF1_SF1PART_INCR', 'EXT_SF1_SF1PART_INIT']
	)
}}
select * from (
	WITH "CALCULATE_BK" AS 
	( 
		SELECT 
			  "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "MEX_SRC"."ATTRIBUTE_VARCHAR" AS "JRN_FLAG"
			, "TDFV_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "TDFV_SRC"."P_PARTKEY" AS "P_PARTKEY"
			, COALESCE(UPPER(REPLACE(TRIM( "TDFV_SRC"."P_NAME"),'^','\\' || '^')),"MEX_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "P_NAME_BK"
			, COALESCE(UPPER( TO_CHAR("TDFV_SRC"."P_SIZE")),"MEX_SRC"."KEY_ATTRIBUTE_NUMBER") AS "P_SIZE_BK"
			, "TDFV_SRC"."P_NAME" AS "P_NAME"
			, "TDFV_SRC"."P_SIZE" AS "P_SIZE"
			, "TDFV_SRC"."P_MFGR" AS "P_MFGR"
			, "TDFV_SRC"."P_BRAND" AS "P_BRAND"
			, "TDFV_SRC"."P_TYPE" AS "P_TYPE"
			, "TDFV_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "TDFV_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "TDFV_SRC"."P_COMMENT" AS "P_COMMENT"
			, "TDFV_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_DFV_VW_SF1_PART') }} "TDFV_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	, "EXT_UNION" AS 
	( 
		SELECT 
			  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
			, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
			, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
			, "CALCULATE_BK"."P_PARTKEY" AS "P_PARTKEY"
			, "CALCULATE_BK"."P_NAME_BK" AS "P_NAME_BK"
			, "CALCULATE_BK"."P_SIZE_BK" AS "P_SIZE_BK"
			, "CALCULATE_BK"."P_NAME" AS "P_NAME"
			, "CALCULATE_BK"."P_SIZE" AS "P_SIZE"
			, "CALCULATE_BK"."P_MFGR" AS "P_MFGR"
			, "CALCULATE_BK"."P_BRAND" AS "P_BRAND"
			, "CALCULATE_BK"."P_TYPE" AS "P_TYPE"
			, "CALCULATE_BK"."P_CONTAINER" AS "P_CONTAINER"
			, "CALCULATE_BK"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "CALCULATE_BK"."P_COMMENT" AS "P_COMMENT"
			, "CALCULATE_BK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "CALCULATE_BK" "CALCULATE_BK"
	)
	SELECT 
		  "EXT_UNION"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_UNION"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_UNION"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_UNION"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_UNION"."P_PARTKEY" AS "P_PARTKEY"
		, "EXT_UNION"."P_NAME_BK" AS "P_NAME_BK"
		, "EXT_UNION"."P_SIZE_BK" AS "P_SIZE_BK"
		, "EXT_UNION"."P_NAME" AS "P_NAME"
		, "EXT_UNION"."P_SIZE" AS "P_SIZE"
		, "EXT_UNION"."P_MFGR" AS "P_MFGR"
		, "EXT_UNION"."P_BRAND" AS "P_BRAND"
		, "EXT_UNION"."P_TYPE" AS "P_TYPE"
		, "EXT_UNION"."P_CONTAINER" AS "P_CONTAINER"
		, "EXT_UNION"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "EXT_UNION"."P_COMMENT" AS "P_COMMENT"
		, "EXT_UNION"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "EXT_UNION" "EXT_UNION"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, TO_CHAR('S') AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."P_PARTKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "P_PARTKEY"
			, "INI_SRC"."P_NAME" AS "P_NAME"
			, "INI_SRC"."P_SIZE" AS "P_SIZE"
			, "INI_SRC"."P_MFGR" AS "P_MFGR"
			, "INI_SRC"."P_BRAND" AS "P_BRAND"
			, "INI_SRC"."P_TYPE" AS "P_TYPE"
			, "INI_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "INI_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "INI_SRC"."P_COMMENT" AS "P_COMMENT"
			, "INI_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('VS_DEMO_TC_INI', 'SF1_PART') }} "INI_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."P_PARTKEY" AS "P_PARTKEY"
			, "LOAD_INIT_DATA"."P_NAME" AS "P_NAME"
			, "LOAD_INIT_DATA"."P_SIZE" AS "P_SIZE"
			, "LOAD_INIT_DATA"."P_MFGR" AS "P_MFGR"
			, "LOAD_INIT_DATA"."P_BRAND" AS "P_BRAND"
			, "LOAD_INIT_DATA"."P_TYPE" AS "P_TYPE"
			, "LOAD_INIT_DATA"."P_CONTAINER" AS "P_CONTAINER"
			, "LOAD_INIT_DATA"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "LOAD_INIT_DATA"."P_COMMENT" AS "P_COMMENT"
			, "LOAD_INIT_DATA"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "P_PARTKEY"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_NAME"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "P_SIZE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_MFGR"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_BRAND"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_TYPE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_CONTAINER"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "P_RETAILPRICE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_COMMENT"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "DSS_RECORD_SOURCE"
		FROM {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."P_PARTKEY" AS "P_PARTKEY"
			, COALESCE(UPPER(REPLACE(TRIM("PREP_EXCEP"."P_NAME"),'^','\\' || '^')),"MEX_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "P_NAME_BK"
			, COALESCE(UPPER( TO_CHAR("PREP_EXCEP"."P_SIZE")),"MEX_SRC"."KEY_ATTRIBUTE_NUMBER") AS "P_SIZE_BK"
			, "PREP_EXCEP"."P_NAME" AS "P_NAME"
			, "PREP_EXCEP"."P_SIZE" AS "P_SIZE"
			, "PREP_EXCEP"."P_MFGR" AS "P_MFGR"
			, "PREP_EXCEP"."P_BRAND" AS "P_BRAND"
			, "PREP_EXCEP"."P_TYPE" AS "P_TYPE"
			, "PREP_EXCEP"."P_CONTAINER" AS "P_CONTAINER"
			, "PREP_EXCEP"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "PREP_EXCEP"."P_COMMENT" AS "P_COMMENT"
			, "PREP_EXCEP"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."P_PARTKEY" AS "P_PARTKEY"
		, "CALCULATE_BK"."P_NAME_BK" AS "P_NAME_BK"
		, "CALCULATE_BK"."P_SIZE_BK" AS "P_SIZE_BK"
		, "CALCULATE_BK"."P_NAME" AS "P_NAME"
		, "CALCULATE_BK"."P_SIZE" AS "P_SIZE"
		, "CALCULATE_BK"."P_MFGR" AS "P_MFGR"
		, "CALCULATE_BK"."P_BRAND" AS "P_BRAND"
		, "CALCULATE_BK"."P_TYPE" AS "P_TYPE"
		, "CALCULATE_BK"."P_CONTAINER" AS "P_CONTAINER"
		, "CALCULATE_BK"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "CALCULATE_BK"."P_COMMENT" AS "P_COMMENT"
		, "CALCULATE_BK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "CALCULATE_BK" "CALCULATE_BK"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'