{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='ORDER_CUST',
		schema='VS_DEMO_TC_EXT',
		tags=['VS_DEMO_TC', 'EXT_SF1_ORDER_CUST_INCR', 'EXT_SF1_ORDER_CUST_INIT']
	)
}}
select * from (
	WITH "CALCULATE_BK" AS 
	( 
		SELECT 
			  "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "MEX_SRC"."ATTRIBUTE_VARCHAR" AS "JRN_FLAG"
			, "TDFV_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "TDFV_SRC"."O_ORDERKEY" AS "O_ORDERKEY"
			, "TDFV_SRC"."O_CUSTKEY" AS "O_CUSTKEY"
			, UPPER( TO_CHAR("TDFV_SRC"."O_ORDERKEY")) AS "O_ORDERKEY_FK_OORDERKEY_BK"
			, "TDFV_SRC"."C_NAME" AS "C_NAME"
		FROM {{ ref('VS_DEMO_TC_DFV_VW_ORDER_CUST') }} "TDFV_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	, "EXT_UNION" AS 
	( 
		SELECT 
			  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
			, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
			, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
			, "CALCULATE_BK"."O_ORDERKEY" AS "O_ORDERKEY"
			, "CALCULATE_BK"."O_CUSTKEY" AS "O_CUSTKEY"
			, "CALCULATE_BK"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
			, "CALCULATE_BK"."C_NAME" AS "C_NAME"
		FROM "CALCULATE_BK" "CALCULATE_BK"
	)
	SELECT 
		  "EXT_UNION"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_UNION"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_UNION"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_UNION"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_UNION"."O_ORDERKEY" AS "O_ORDERKEY"
		, "EXT_UNION"."O_CUSTKEY" AS "O_CUSTKEY"
		, "EXT_UNION"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
		, "EXT_UNION"."C_NAME" AS "C_NAME"
	FROM "EXT_UNION" "EXT_UNION"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT DISTINCT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, TO_CHAR('S') AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."O_ORDERKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "O_ORDERKEY"
			, COALESCE("INI_SRC"."O_CUSTKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "O_CUSTKEY"
			, "INI_SRC"."C_NAME" AS "C_NAME"
		FROM {{ source('VS_DEMO_TC_INI', 'SF1_ORDERS') }} "INI_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."O_ORDERKEY" AS "O_ORDERKEY"
			, "LOAD_INIT_DATA"."O_CUSTKEY" AS "O_CUSTKEY"
			, "LOAD_INIT_DATA"."C_NAME" AS "C_NAME"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "O_ORDERKEY"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "O_CUSTKEY"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "C_NAME"
		FROM {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."O_ORDERKEY" AS "O_ORDERKEY"
			, "PREP_EXCEP"."O_CUSTKEY" AS "O_CUSTKEY"
			, UPPER( TO_CHAR("PREP_EXCEP"."O_ORDERKEY")) AS "O_ORDERKEY_FK_OORDERKEY_BK"
			, "PREP_EXCEP"."C_NAME" AS "C_NAME"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."O_ORDERKEY" AS "O_ORDERKEY"
		, "CALCULATE_BK"."O_CUSTKEY" AS "O_CUSTKEY"
		, "CALCULATE_BK"."O_ORDERKEY_FK_OORDERKEY_BK" AS "O_ORDERKEY_FK_OORDERKEY_BK"
		, "CALCULATE_BK"."C_NAME" AS "C_NAME"
	FROM "CALCULATE_BK" "CALCULATE_BK"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'