{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_SUPPLIER',
		schema='VS_DEMO_TC_EXT',
		tags=['VS_DEMO_TC', 'EXT_SF1_SF1SUPPLIER_INCR', 'EXT_SF1_SF1SUPPLIER_INIT']
	)
}}
select * from (
	WITH "CALCULATE_BK" AS 
	( 
		SELECT 
			  "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "MEX_SRC"."ATTRIBUTE_VARCHAR" AS "JRN_FLAG"
			, "TDFV_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "TDFV_SRC"."S_SUPPKEY" AS "S_SUPPKEY"
			, COALESCE(UPPER(REPLACE(TRIM( "TDFV_SRC"."S_NAME"),'^','\\' || '^')),"MEX_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "S_NAME_BK"
			, "TDFV_SRC"."S_NAME" AS "S_NAME"
			, "TDFV_SRC"."S_ADDRESS" AS "S_ADDRESS"
			, "TDFV_SRC"."S_NATIONKEY" AS "S_NATIONKEY"
			, "TDFV_SRC"."S_PHONE" AS "S_PHONE"
			, "TDFV_SRC"."S_ACCTBAL" AS "S_ACCTBAL"
			, "TDFV_SRC"."S_COMMENT" AS "S_COMMENT"
			, "TDFV_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_DFV_VW_SF1_SUPPLIER') }} "TDFV_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	, "EXT_UNION" AS 
	( 
		SELECT 
			  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
			, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
			, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
			, "CALCULATE_BK"."S_SUPPKEY" AS "S_SUPPKEY"
			, "CALCULATE_BK"."S_NAME_BK" AS "S_NAME_BK"
			, "CALCULATE_BK"."S_NAME" AS "S_NAME"
			, "CALCULATE_BK"."S_ADDRESS" AS "S_ADDRESS"
			, "CALCULATE_BK"."S_NATIONKEY" AS "S_NATIONKEY"
			, "CALCULATE_BK"."S_PHONE" AS "S_PHONE"
			, "CALCULATE_BK"."S_ACCTBAL" AS "S_ACCTBAL"
			, "CALCULATE_BK"."S_COMMENT" AS "S_COMMENT"
			, "CALCULATE_BK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "CALCULATE_BK" "CALCULATE_BK"
	)
	SELECT 
		  "EXT_UNION"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_UNION"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_UNION"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_UNION"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_UNION"."S_SUPPKEY" AS "S_SUPPKEY"
		, "EXT_UNION"."S_NAME_BK" AS "S_NAME_BK"
		, "EXT_UNION"."S_NAME" AS "S_NAME"
		, "EXT_UNION"."S_ADDRESS" AS "S_ADDRESS"
		, "EXT_UNION"."S_NATIONKEY" AS "S_NATIONKEY"
		, "EXT_UNION"."S_PHONE" AS "S_PHONE"
		, "EXT_UNION"."S_ACCTBAL" AS "S_ACCTBAL"
		, "EXT_UNION"."S_COMMENT" AS "S_COMMENT"
		, "EXT_UNION"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "EXT_UNION" "EXT_UNION"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, TO_CHAR('S') AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."S_SUPPKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "S_SUPPKEY"
			, "INI_SRC"."S_NAME" AS "S_NAME"
			, "INI_SRC"."S_ADDRESS" AS "S_ADDRESS"
			, "INI_SRC"."S_NATIONKEY" AS "S_NATIONKEY"
			, "INI_SRC"."S_PHONE" AS "S_PHONE"
			, "INI_SRC"."S_ACCTBAL" AS "S_ACCTBAL"
			, "INI_SRC"."S_COMMENT" AS "S_COMMENT"
			, "INI_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('VS_DEMO_TC_INI', 'SF1_SUPPLIER') }} "INI_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."S_SUPPKEY" AS "S_SUPPKEY"
			, "LOAD_INIT_DATA"."S_NAME" AS "S_NAME"
			, "LOAD_INIT_DATA"."S_ADDRESS" AS "S_ADDRESS"
			, "LOAD_INIT_DATA"."S_NATIONKEY" AS "S_NATIONKEY"
			, "LOAD_INIT_DATA"."S_PHONE" AS "S_PHONE"
			, "LOAD_INIT_DATA"."S_ACCTBAL" AS "S_ACCTBAL"
			, "LOAD_INIT_DATA"."S_COMMENT" AS "S_COMMENT"
			, "LOAD_INIT_DATA"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "S_SUPPKEY"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_VARCHAR" AS VARCHAR) AS "S_NAME"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "S_ADDRESS"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "S_NATIONKEY"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "S_PHONE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "S_ACCTBAL"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "S_COMMENT"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "DSS_RECORD_SOURCE"
		FROM {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."S_SUPPKEY" AS "S_SUPPKEY"
			, COALESCE(UPPER(REPLACE(TRIM("PREP_EXCEP"."S_NAME"),'^','\\' || '^')),"MEX_SRC"."KEY_ATTRIBUTE_VARCHAR") AS "S_NAME_BK"
			, "PREP_EXCEP"."S_NAME" AS "S_NAME"
			, "PREP_EXCEP"."S_ADDRESS" AS "S_ADDRESS"
			, "PREP_EXCEP"."S_NATIONKEY" AS "S_NATIONKEY"
			, "PREP_EXCEP"."S_PHONE" AS "S_PHONE"
			, "PREP_EXCEP"."S_ACCTBAL" AS "S_ACCTBAL"
			, "PREP_EXCEP"."S_COMMENT" AS "S_COMMENT"
			, "PREP_EXCEP"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."S_SUPPKEY" AS "S_SUPPKEY"
		, "CALCULATE_BK"."S_NAME_BK" AS "S_NAME_BK"
		, "CALCULATE_BK"."S_NAME" AS "S_NAME"
		, "CALCULATE_BK"."S_ADDRESS" AS "S_ADDRESS"
		, "CALCULATE_BK"."S_NATIONKEY" AS "S_NATIONKEY"
		, "CALCULATE_BK"."S_PHONE" AS "S_PHONE"
		, "CALCULATE_BK"."S_ACCTBAL" AS "S_ACCTBAL"
		, "CALCULATE_BK"."S_COMMENT" AS "S_COMMENT"
		, "CALCULATE_BK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "CALCULATE_BK" "CALCULATE_BK"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'