{{
	config(
		materialized='incremental',
		pre_hook= [
			'{% if var("load_type") == "INCR" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}',
			'{% if var("load_type") == "INIT" and var("source") == "VS_DEMO_TC" %} TRUNCATE TABLE {{ this }}; {% endif %}'
		],
		alias='SF1_LINEITEM',
		schema='VS_DEMO_TC_EXT',
		tags=['VS_DEMO_TC', 'EXT_SF1_SF1LINEITEM_INCR', 'EXT_SF1_SF1LINEITEM_INIT']
	)
}}
select * from (
	WITH "CALCULATE_BK" AS 
	( 
		SELECT 
			  "LCI_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "MEX_SRC"."ATTRIBUTE_VARCHAR" AS "JRN_FLAG"
			, "TDFV_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "TDFV_SRC"."L_ORDERKEY" AS "L_ORDERKEY"
			, "TDFV_SRC"."L_LINENUMBER" AS "L_LINENUMBER"
			, "TDFV_SRC"."L_PARTKEY" AS "L_PARTKEY"
			, "TDFV_SRC"."L_SUPPKEY" AS "L_SUPPKEY"
			, UPPER( TO_CHAR("TDFV_SRC"."L_ORDERKEY")) AS "O_ORDERKEY_FK_LORDERKEY_BK"
			, "TDFV_SRC"."P_NAME" AS "P_NAME"
			, "TDFV_SRC"."P_SIZE" AS "P_SIZE"
			, "TDFV_SRC"."S_NAME" AS "S_NAME"
			, "TDFV_SRC"."L_QUANTITY" AS "L_QUANTITY"
			, "TDFV_SRC"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "TDFV_SRC"."L_DISCOUNT" AS "L_DISCOUNT"
			, "TDFV_SRC"."L_TAX" AS "L_TAX"
			, "TDFV_SRC"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "TDFV_SRC"."L_LINESTATUS" AS "L_LINESTATUS"
			, "TDFV_SRC"."L_SHIPDATE" AS "L_SHIPDATE"
			, "TDFV_SRC"."L_COMMITDATE" AS "L_COMMITDATE"
			, "TDFV_SRC"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "TDFV_SRC"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "TDFV_SRC"."L_SHIPMODE" AS "L_SHIPMODE"
			, "TDFV_SRC"."L_COMMENT" AS "L_COMMENT"
			, "TDFV_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ ref('VS_DEMO_TC_DFV_VW_SF1_LINEITEM') }} "TDFV_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	, "EXT_UNION" AS 
	( 
		SELECT 
			  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
			, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
			, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
			, "CALCULATE_BK"."L_ORDERKEY" AS "L_ORDERKEY"
			, "CALCULATE_BK"."L_LINENUMBER" AS "L_LINENUMBER"
			, "CALCULATE_BK"."L_PARTKEY" AS "L_PARTKEY"
			, "CALCULATE_BK"."L_SUPPKEY" AS "L_SUPPKEY"
			, "CALCULATE_BK"."O_ORDERKEY_FK_LORDERKEY_BK" AS "O_ORDERKEY_FK_LORDERKEY_BK"
			, "CALCULATE_BK"."P_NAME" AS "P_NAME"
			, "CALCULATE_BK"."P_SIZE" AS "P_SIZE"
			, "CALCULATE_BK"."S_NAME" AS "S_NAME"
			, "CALCULATE_BK"."L_QUANTITY" AS "L_QUANTITY"
			, "CALCULATE_BK"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "CALCULATE_BK"."L_DISCOUNT" AS "L_DISCOUNT"
			, "CALCULATE_BK"."L_TAX" AS "L_TAX"
			, "CALCULATE_BK"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "CALCULATE_BK"."L_LINESTATUS" AS "L_LINESTATUS"
			, "CALCULATE_BK"."L_SHIPDATE" AS "L_SHIPDATE"
			, "CALCULATE_BK"."L_COMMITDATE" AS "L_COMMITDATE"
			, "CALCULATE_BK"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "CALCULATE_BK"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "CALCULATE_BK"."L_SHIPMODE" AS "L_SHIPMODE"
			, "CALCULATE_BK"."L_COMMENT" AS "L_COMMENT"
			, "CALCULATE_BK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "CALCULATE_BK" "CALCULATE_BK"
	)
	SELECT 
		  "EXT_UNION"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "EXT_UNION"."LOAD_DATE" AS "LOAD_DATE"
		, "EXT_UNION"."JRN_FLAG" AS "JRN_FLAG"
		, "EXT_UNION"."RECORD_TYPE" AS "RECORD_TYPE"
		, "EXT_UNION"."L_ORDERKEY" AS "L_ORDERKEY"
		, "EXT_UNION"."L_LINENUMBER" AS "L_LINENUMBER"
		, "EXT_UNION"."L_PARTKEY" AS "L_PARTKEY"
		, "EXT_UNION"."L_SUPPKEY" AS "L_SUPPKEY"
		, "EXT_UNION"."O_ORDERKEY_FK_LORDERKEY_BK" AS "O_ORDERKEY_FK_LORDERKEY_BK"
		, "EXT_UNION"."P_NAME" AS "P_NAME"
		, "EXT_UNION"."P_SIZE" AS "P_SIZE"
		, "EXT_UNION"."S_NAME" AS "S_NAME"
		, "EXT_UNION"."L_QUANTITY" AS "L_QUANTITY"
		, "EXT_UNION"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
		, "EXT_UNION"."L_DISCOUNT" AS "L_DISCOUNT"
		, "EXT_UNION"."L_TAX" AS "L_TAX"
		, "EXT_UNION"."L_RETURNFLAG" AS "L_RETURNFLAG"
		, "EXT_UNION"."L_LINESTATUS" AS "L_LINESTATUS"
		, "EXT_UNION"."L_SHIPDATE" AS "L_SHIPDATE"
		, "EXT_UNION"."L_COMMITDATE" AS "L_COMMITDATE"
		, "EXT_UNION"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
		, "EXT_UNION"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
		, "EXT_UNION"."L_SHIPMODE" AS "L_SHIPMODE"
		, "EXT_UNION"."L_COMMENT" AS "L_COMMENT"
		, "EXT_UNION"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "EXT_UNION" "EXT_UNION"

) final 
where '{{ var("load_type") }}' = 'INCR' and '{{ var("source") }}' = 'VS_DEMO_TC'

UNION ALL

select * from (
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, TO_CHAR('S') AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."L_ORDERKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_ORDERKEY"
			, COALESCE("INI_SRC"."L_LINENUMBER", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_LINENUMBER"
			, COALESCE("INI_SRC"."L_PARTKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_PARTKEY"
			, COALESCE("INI_SRC"."L_SUPPKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER)) AS "L_SUPPKEY"
			, "INI_SRC"."P_NAME" AS "P_NAME"
			, "INI_SRC"."P_SIZE" AS "P_SIZE"
			, "INI_SRC"."S_NAME" AS "S_NAME"
			, "INI_SRC"."L_QUANTITY" AS "L_QUANTITY"
			, "INI_SRC"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "INI_SRC"."L_DISCOUNT" AS "L_DISCOUNT"
			, "INI_SRC"."L_TAX" AS "L_TAX"
			, "INI_SRC"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "INI_SRC"."L_LINESTATUS" AS "L_LINESTATUS"
			, "INI_SRC"."L_SHIPDATE" AS "L_SHIPDATE"
			, "INI_SRC"."L_COMMITDATE" AS "L_COMMITDATE"
			, "INI_SRC"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "INI_SRC"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "INI_SRC"."L_SHIPMODE" AS "L_SHIPMODE"
			, "INI_SRC"."L_COMMENT" AS "L_COMMENT"
			, "INI_SRC"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM {{ source('VS_DEMO_TC_INI', 'SF1_LINEITEM') }} "INI_SRC"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."L_ORDERKEY" AS "L_ORDERKEY"
			, "LOAD_INIT_DATA"."L_LINENUMBER" AS "L_LINENUMBER"
			, "LOAD_INIT_DATA"."L_PARTKEY" AS "L_PARTKEY"
			, "LOAD_INIT_DATA"."L_SUPPKEY" AS "L_SUPPKEY"
			, "LOAD_INIT_DATA"."P_NAME" AS "P_NAME"
			, "LOAD_INIT_DATA"."P_SIZE" AS "P_SIZE"
			, "LOAD_INIT_DATA"."S_NAME" AS "S_NAME"
			, "LOAD_INIT_DATA"."L_QUANTITY" AS "L_QUANTITY"
			, "LOAD_INIT_DATA"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "LOAD_INIT_DATA"."L_DISCOUNT" AS "L_DISCOUNT"
			, "LOAD_INIT_DATA"."L_TAX" AS "L_TAX"
			, "LOAD_INIT_DATA"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "LOAD_INIT_DATA"."L_LINESTATUS" AS "L_LINESTATUS"
			, "LOAD_INIT_DATA"."L_SHIPDATE" AS "L_SHIPDATE"
			, "LOAD_INIT_DATA"."L_COMMITDATE" AS "L_COMMITDATE"
			, "LOAD_INIT_DATA"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "LOAD_INIT_DATA"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "LOAD_INIT_DATA"."L_SHIPMODE" AS "L_SHIPMODE"
			, "LOAD_INIT_DATA"."L_COMMENT" AS "L_COMMENT"
			, "LOAD_INIT_DATA"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  TO_CHAR('I' ) AS "JRN_FLAG"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "L_ORDERKEY"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "L_LINENUMBER"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "L_PARTKEY"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_NUMBER" AS NUMBER) AS "L_SUPPKEY"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_NAME"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "P_SIZE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "S_NAME"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "L_QUANTITY"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "L_EXTENDEDPRICE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "L_DISCOUNT"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_NUMBER" AS NUMBER) AS "L_TAX"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "L_RETURNFLAG"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "L_LINESTATUS"
			, TO_DATE("MEX_EXT_SRC"."ATTRIBUTE_DATE", 'DD/MM/YYYY') AS "L_SHIPDATE"
			, TO_DATE("MEX_EXT_SRC"."ATTRIBUTE_DATE", 'DD/MM/YYYY') AS "L_COMMITDATE"
			, TO_DATE("MEX_EXT_SRC"."ATTRIBUTE_DATE", 'DD/MM/YYYY') AS "L_RECEIPTDATE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "L_SHIPINSTRUCT"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "L_SHIPMODE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "L_COMMENT"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "DSS_RECORD_SOURCE"
		FROM {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."L_ORDERKEY" AS "L_ORDERKEY"
			, "PREP_EXCEP"."L_LINENUMBER" AS "L_LINENUMBER"
			, "PREP_EXCEP"."L_PARTKEY" AS "L_PARTKEY"
			, "PREP_EXCEP"."L_SUPPKEY" AS "L_SUPPKEY"
			, UPPER( TO_CHAR("PREP_EXCEP"."L_ORDERKEY")) AS "O_ORDERKEY_FK_LORDERKEY_BK"
			, "PREP_EXCEP"."P_NAME" AS "P_NAME"
			, "PREP_EXCEP"."P_SIZE" AS "P_SIZE"
			, "PREP_EXCEP"."S_NAME" AS "S_NAME"
			, "PREP_EXCEP"."L_QUANTITY" AS "L_QUANTITY"
			, "PREP_EXCEP"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
			, "PREP_EXCEP"."L_DISCOUNT" AS "L_DISCOUNT"
			, "PREP_EXCEP"."L_TAX" AS "L_TAX"
			, "PREP_EXCEP"."L_RETURNFLAG" AS "L_RETURNFLAG"
			, "PREP_EXCEP"."L_LINESTATUS" AS "L_LINESTATUS"
			, "PREP_EXCEP"."L_SHIPDATE" AS "L_SHIPDATE"
			, "PREP_EXCEP"."L_COMMITDATE" AS "L_COMMITDATE"
			, "PREP_EXCEP"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
			, "PREP_EXCEP"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
			, "PREP_EXCEP"."L_SHIPMODE" AS "L_SHIPMODE"
			, "PREP_EXCEP"."L_COMMENT" AS "L_COMMENT"
			, "PREP_EXCEP"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'LOAD_CYCLE_INFO') }} "LCI_SRC" ON  1 = 1
		INNER JOIN {{ source('VS_DEMO_TC_MTD', 'MTD_EXCEPTION_RECORDS') }} "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."L_ORDERKEY" AS "L_ORDERKEY"
		, "CALCULATE_BK"."L_LINENUMBER" AS "L_LINENUMBER"
		, "CALCULATE_BK"."L_PARTKEY" AS "L_PARTKEY"
		, "CALCULATE_BK"."L_SUPPKEY" AS "L_SUPPKEY"
		, "CALCULATE_BK"."O_ORDERKEY_FK_LORDERKEY_BK" AS "O_ORDERKEY_FK_LORDERKEY_BK"
		, "CALCULATE_BK"."P_NAME" AS "P_NAME"
		, "CALCULATE_BK"."P_SIZE" AS "P_SIZE"
		, "CALCULATE_BK"."S_NAME" AS "S_NAME"
		, "CALCULATE_BK"."L_QUANTITY" AS "L_QUANTITY"
		, "CALCULATE_BK"."L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE"
		, "CALCULATE_BK"."L_DISCOUNT" AS "L_DISCOUNT"
		, "CALCULATE_BK"."L_TAX" AS "L_TAX"
		, "CALCULATE_BK"."L_RETURNFLAG" AS "L_RETURNFLAG"
		, "CALCULATE_BK"."L_LINESTATUS" AS "L_LINESTATUS"
		, "CALCULATE_BK"."L_SHIPDATE" AS "L_SHIPDATE"
		, "CALCULATE_BK"."L_COMMITDATE" AS "L_COMMITDATE"
		, "CALCULATE_BK"."L_RECEIPTDATE" AS "L_RECEIPTDATE"
		, "CALCULATE_BK"."L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT"
		, "CALCULATE_BK"."L_SHIPMODE" AS "L_SHIPMODE"
		, "CALCULATE_BK"."L_COMMENT" AS "L_COMMENT"
		, "CALCULATE_BK"."DSS_RECORD_SOURCE" AS "DSS_RECORD_SOURCE"
	FROM "CALCULATE_BK" "CALCULATE_BK"

) final 
where '{{ var("load_type") }}' = 'INIT' and '{{ var("source") }}' = 'VS_DEMO_TC'